const servicios = [
    '4/12/2022,20,Sin comunicación,Registrador sin comunicación,No,Se encuentra registrador con alimentación correcta pero apagado.,',
    '10/25/2022,20,Sin comunicación,Antena mal orientada,Sí,Se reoriento antena.,no aplica',
    '8/3/2022,28,Sin comunicación,Registrador sin comunicación y Alarma de ausencia de 220Vca,Sí,Se reemplazo placa de encendido por tener tecla de encendido dañada.,',
    '9/21/2022,36,Sin comunicación,Antena con elemento dañado.,Sí,Se reemplazo antena.,',
    '9/29/2022,36,Sin comunicación,Radiomodem con mal funcionaiento.,Sí,se reemplazo radiomodem,no aplica',
    '11/4/2022,85,Sin comunicación,registrador desconfigurado.,Sí,Se reconfiguro registrador.,Se normalizo conexiones del registrador.',
    '11/14/2022,146,Sin comunicación,Caja de protección dañada por sobretensión,Sí,"Se reemplazo chapa completa (chapa, borneras fronteras, cables, placa, borneras enchufables) de la caja de protección.",Se solicito un corte de en MT para trabajar en el reemplazo de los elementos dañados.',
    '1/10/2022,Puesto de compra,Mala comunicación,,Sí,Se cambio cable coaxial y antena.,',
    '7/4/2022,207,Sin comunicación,Batería dañada,Sí,Se reemplazo batería y placa de control.,Se instalo vinculación a Tierra al gabiente de punto fijo ya que no la tenia.',
    '2/4/2022,249,Sin comunicación,Radiomodem con mal funcionaiento.,Sí,Se reemplazo radiomodem,',
    '1/11/2022,3749,Mala comunicación,,Sí,Se cambió cable coaxial dañado,',
    '1/11/2022,813,Otros,Corriente R y T con valores de 0 Amp,Sí,Borneras de medición de corriente en el registrador estan quemadas. Se debe cambiar registrador y cables de corrientes. Solo se corrigió corriente de la fase T.,',
    '5/20/2022,267,Sin comunicación,Registrador sin comunicación. Cables de comunicación sueltos.,Sí,Se ajustaron cables de comunicación en borneras del registrador.,',
    '5/26/2022,411,Sin comunicación,Radiomodem con mal funcionamiento.,Sí,Se reemplazo radiomodem,se encontro el equipo sin batería. Se coloco una betría nueva.',
    '12/5/2022,452,Sin comunicación,Registrador sin comunicación.,Sí,Se reconfiguro registrador.,Se configuro un TI de 500/5',
    '1/13/2022,,Mala comunicación,La fuente que alimenta el conversor RS232 a Ethernet se encuentra dañada,Sí,Se reemplaza fuente,Se coloca fuente provisoria.',
    '1/14/2022,Los Ralos - Operaciones,Preventivo,,,Quedo pendiente reemplazar fuente y conversor,',
    '1/14/2022,2476,Otros,Nos solicitaron modificar la configuración del registrador de monofásico a trifásico,Sí,Se reconfiguro registrador y se modifico en sistema SCADA,',
    '12/20/2022,482,Sin comunicación,error de comunicación,No,Se reemplazo radiomodem pero no se retablecio la comunicación. Queda pendiente revisar cable coaxial y antena,Es necesario realizar un corte de energía para acceder hasta la antena y verificar su estado.',
    '7/13/2022,504,Sin comunicación,Placa rtu y registrador sin comunicación,Sí,Se ajustaron cables de alimentación en placa RTU.,',
    '1/17/2022,ET Avellaneda - TELGECS,Preventivo,,,,',
    '1/17/2022,2246,Preventivo,,,,',
    '6/14/2022,505,Sin comunicación,Radiomodem sin recepción de señal,Sí,Se reemplazo radiomodem,',
    '1/18/2022,Estática Sur,Preventivo,,,,Descarga de datos.',
    '1/18/2022,Sarmiento,Preventivo,,,,Descarga de datos.',
    '5/30/2022,548,Sin comunicación,antena mal orientada.,Sí,Se reoriento antena.,',
    '2/9/2022,554,Sin comunicación,Indica Ausencia de 220.,Sí,Se cambio placa de encendido dañada,Se encontro hormigas dentro de la caja de protección.',
    '3/11/2022,554,Sin comunicación,Equipo sin comunicación,Sí,Se cambio placa de control dañada.,',
    '6/14/2022,554,Sin comunicación,Registrador sin comunicación,Sí,Se reseteo el registrador y levanto la comunicación.,Registrador con mal funcionamiento.',
    '4/20/2022,566,Sin comunicación,Placa de control no entrega alimentación de continua,No,Se cambio placa de control.,No se pudo probar el resultado del trabajo realizado ya que durante la tarea NOANET realizo mantenimiento en el sistema. Queda pendiente de verificacion',
    '4/26/2022,588,Sin comunicación,A determinar,No,"Se cambio radiomodem y se observo coaxial y antena en buen estado, pero no se llego a una solución",Posible falla en la Repetidora del Este TELGECS.',
    '1/20/2022,504,Preventivo,,,,',
    '1/20/2022,932,Preventivo,,,,',
    '1/20/2022,2889,Preventivo,,,,',
    '1/20/2022,3257,Preventivo,,,,',
    '1/21/2022,Via Ruta 336,Sin lectura,Se encuentra sin lectura el estado del reconectador,No,Se observa que llegan desde la caja de control 110Vca en las dos señales que corresponden a la entra digital 4 y 5 de la placa RTU (señales dobles que indican el estado del reconectador). Se da aviso a  personal de equipo electrico para que se revise el problema.,',
    '2/25/2022,626,Sin comunicación,Equipo sin comunicación,,,',
    '2/25/2022,632,Sin comunicación,Equipo sin comunicación,,,',
    '1/24/2022,La Rural,Sin lectura,Placa RTU Número 3 dañada,Sí,Se reparo placa RTU número 3,',
    '1/24/2022,Concepcion 2,Sin lectura,Placa RTU de control con fusible quemado.,Sí,Se reemplazo fusible en placa RTU de control.,',
    '1/25/2022,1584,Otros,registrador no bajaba registros.,No,se bajaron datos a pie de equipo y se observa que posee un registro del año 2046. Se borran datos y se reconfigura pero continua con problema para generar registros.,Se aconseja cambiar el registrador. Se informo atraves de un correo electrónico.',
    '10/5/2022,670,Sin comunicación,Antena mal orientada,Sí,Se reoriento anteja y se ajusto.,no aplica',
    '11/4/2022,780,Sin comunicación,Línea de vista obstruida,Sí,Se reoriento antena.,Construcción de dos plantas obstruye linea de vista.',
    '1/26/2022,Ampimpa - Operaciones,Otros,Se verifica el estado de la base ya que el reconectador puesto de compra presenta error de comunicación,Sí,Se cambia orientacion de antena y levanto la comunicación del reconectador Puesto de Compra.,',
    '2/9/2022,813,Sin comunicación,Placa de control dañada.,Sí,Se reemplazó placa de control.,Se encontraron dañadas dos borneras de corriente del analizador y cables en mal estado. Se deben reemplazar el analizador y los cables.',
    '10/12/2022,901,Sin comunicación,Antena dañada,Sí,El equipo queda comunicado pero con algunos errores de comunicación. .,Se realizara un seguimiento de dicho equipo para ver su funcionamiento y de ser necesario se coordinara una visita al mismo.',
    '1/26/2022,Amaicha - TELGECS,Preventivo,,,,',
    '8/12/2022,918,Sin comunicación,Placa de control no entrega alimentación de continua.,Sí,Se cambió placa de control y una ficha conectada a dicha placa.,',
    '2/16/2022,976,Sin comunicación,Equipo sin comunicación,,,',
    '1/27/2022,2246,Otros,Medición de corriente en las tres fases de 0 Amp.,Sí,se quitaron puentes en borneras de corriente en caja de protección y se configuro registrador con TI de 500/5,',
    '2/18/2022,976,Sin comunicación,Registrador sin comunicación,Sí,Se reconfiguro registrador.,Se normalizaron conexiones del registrador.',
    '5/9/2022,994,Sin comunicación,Todo el equipo sin comunicación.,Sí,Se reemplazo radiomodem,',
    '11/22/2022,1018,Sin comunicación,Radiomodem con fusible quemado.,Sí,se reemplazo radiomodem,no aplica.',
    '1/28/2022,2857,Mala comunicación,Presenta errores de comunicación,Sí,Se cambio radiomodem,',
    '2/1/2022,6688,Preventivo,,,,',
    '4/8/2022,1107,Sin comunicación,antena mal orientada,Sí,Se reoriento antena.,',
    '9/12/2022,1141,Sin comunicación,Sin comunicación con placa RTU,Sí,Placa RTU dañada. Se reemplazó.,no aplica',
    '9/14/2022,1141,Sin comunicación,Registrador y placa RTU sin comunicación,Sí,Se reemplazo placa RTU,no aplica',
    '7/5/2022,1145,Sin comunicación,Radiomodem con mal funcionamiento.,Sí,Se reemplazo radiomodem.,',
    '2/2/2022,976,Preventivo,,,,',
    '4/26/2022,1160,Sin comunicación,Registrador sin comunicación.,Sí,Se conectaron cables de comunicación sueltos en el registrador,',
    '2/2/2022,1947,Preventivo,,,,',
    '2/2/2022,510,Preventivo,,,,',
    '2/22/2022,1173,Sin comunicación,Registrador sin comunicación,Sí,se reconfigura velocidad del registrador.,El equipo queda con mala comunicacion. Se solicita un corte para acceder hasta la antena y verificar su estado.',
    '2/3/2022,Trinidad,Preventivo,,,,',
    '3/28/2022,1173,Sin comunicación,Batería agotada,No,No se dispone de baterías para realizar el reemplazo. Queda previsto regresar para dar solución.,',
    '2/3/2022,2800,Preventivo,,,,',
    '2/3/2022,2030,Preventivo,,,,',
    '3/31/2022,1173,Sin comunicación,batería agotada.,Sí," La batería se encuentra dañada, al no tener para reemplazarla se deja la misma desconectada. Se realizo reemplazo de radiomodem. ","El equipo queda con mala comunicación y para solucinarlo es necesario verificar el estado de cable coaxial y antena, para ello es necesario coordinar una tarea y disponer de una barquilla. "',
    '6/29/2022,1194,Sin comunicación,Placa de control dañada.,Sí,se reemplazo placa de control,',
    '2/4/2022,Der. A Mista,Otros,No se ejecutan los comandos.,Sí,Se realizo limpieza de los contactos de la manguera que vincula RTU con caja de control. Se probo un comando de recierre con resultados positivos.,Queda pendiente realizar comandos de apertura y cierre.',
    '2/4/2022,Arr. Mista,Preventivo,,,,',
    '10/19/2022,1197,Sin comunicación,Este es uno de los equipos que se encuentra sin comunicación pertenecientes a la BASE CON-TELGECS,No,Se realizaron diversas pruebas pero no se logra a una solucion,no aplica',
    '2/7/2022,Alderetes,Otros,Inspeccion,Sí,Se verifica que las comunicaciones no fueron afetadas por el robo sufrido el fin de semana.,',
    '10/24/2022,1197,Sin comunicación,A determinar,Sí,Se cambio canal de comunicación,no aplica.',
    '11/3/2022,1197,Sin comunicación,Radiomodem con fusible quemado.,Sí,Se reemplazo radiomodem,no aplica.',
    '12/15/2022,1197,Sin comunicación,Sin comunicación RTU y Analizador,Sí,Se ajustaron cables de alimentación con falso contacto,no aplica',
    '5/5/2022,1250,Sin comunicación,,,,',
    '5/19/2022,1250,Sin comunicación,Linea de vista obstruida,Sí,Se modifico el canal de comunicación por C4-Ñuñorco.,',
    '2/4/2022,1389,Sin comunicación,Placa de control dañada.,Sí,Se reemplazo placa de control.,',
    '2/8/2022,6964,Preventivo,,,,No tiene los TI.',
    '2/8/2022,2835,Preventivo,,,,',
    '2/3/2022,1397,Sin comunicación,Placa de control no entrega alimentación de continua,Sí,Se cambio placa de control.,',
    '7/12/2022,1397,Sin comunicación,Con error de comunicación y alarma de ausencia de 220Vca.,Sí,"Se reemplazo placa de control, Placa de protección y placa de encendido. Todas dañadas por una sobretensión",',
    '10/20/2022,1397,Sin comunicación,Este es uno de los equipos que se encuentra sin comunicación pertenecientes a la BASE CON-TELGECS,No,Se realizaron diversas pruebas pero no se logra a una solucion,no aplica',
    '10/24/2022,1397,Sin comunicación,A determinar,Sí,Se cambio canal de comunicación,Se soluciono a demas una alarma de ausencia de Fase.',
    '2/9/2022,1107,Preventivo,,,,',
    '2/10/2022,4124,Preventivo,,,,',
    '2/10/2022,3100,Preventivo,,,,',
    '2/10/2022,3099,Preventivo,,,,',
    '9/9/2022,1520,Sin comunicación,Sin comunicación con analizador,No,Analizador no enciende. Se debe reemplazar. Se avisa a personal de Adm. Banda.,no aplica',
    '11/3/2022,1554,Sin comunicación,Mala comunicación,Sí,Se reemplazo radiomodem,no aplica.',
    '2/14/2022,Ñuñorco - Operaciones y TELGECS,Otros,Sin alimentación de 220Vca,Sí,Se reemplaza tramo de la línea de 220Vca que se encontraba cortado.,',
    '8/1/2022,1651,Sin comunicación,Registrador sin comunicación.,Sí,Se reemplazo cable de comunicación del registrador por estar cortado.,',
    '2/15/2022,1133,Preventivo,,,,',
    '2/15/2022,1932,Preventivo,,,,',
    '2/16/2022,1830,Preventivo,cambiar radiomodem,,,',
    '6/9/2022,1698,Sin comunicación,Radiomodem con fusible quemado.,Sí,Se reemplazo radiomodem,',
    '9/22/2022,1801,Sin comunicación,Placa de control dañada,Sí,Se reemplazo placa de control.,no aplica',
    '3/8/2022,1811,Sin comunicación,Equipo sin comunicación,Sí,Se cambio radiomdem por problema de comunicación.,',
    '10/5/2022,1811,Sin comunicación,Al llegar el sitio el equipo preentaba comunicación correcta.,Sí,Se realizo medición de tensiones y verificacion de la exixtencia de algun falso contacto pero no se detecto ninguna posible falla. Se reemplazo radiomodem y se verificara su funcionamiento en los proximos dias.,no aplica',
    '4/19/2022,1861,Sin comunicación,placa RTU dañada,Sí,Se reemplazo placa RTU,',
    '4/26/2022,1874,Sin comunicación,A determinar,No,"Se cambio radiomodem y se observo coaxial y antena en buen estado, pero no se llego a una solución",Posible falla en la Repetidora del Este TELGECS.',
    '2/21/2022,Se trabajo en RACO,,,,,',
    '1/11/2022,1895,Sin comunicación,Registrador y placa RTU sin comunicación,Sí,Se cambio placa de control,',
    '12/21/2022,1939,Sin comunicación,error de comunicación,No,No se pudo ingresar a la propiedad privada donde se encuentra la SET,"Se solicita cambiar de posición el equipo,girar hacia la calle y ponerlo por debajo de la linea de  baja tensión"',
    '12/23/2022,1939,Sin comunicación,Radiomodem con fusible quemado.,Sí,Se reemplazo radiomodem,No aplica',
    '2/22/2022,La Rural,Mala comunicación,Cayó una rama sobre la antena quedando la misma mal orientada,Sí,Se quito rama de sobre la antena y se reoriento la misma.,',
    '6/28/2022,1947,Sin comunicación,Placa de control dañada.,Sí,Se cambio placa de control.,',
    '2/2/2022,1951,Sin comunicación,Registrador sin comunicación,Sí,Se cambio cable de comunicación de registrador por estar cortado.,',
    '2/23/2022,3879,Preventivo,,,,',
    '2/8/2022,1987,Sin comunicación,Placa de protección dañada.,Sí,Se cambió placa de protección.,',
    '11/2/2022,1987,Sin comunicación,Placa de proteccion dañada,Sí,Se reemplazo placa de proteccion y se cambio batería por estar agotada.,Al llegar al sitio el registrador se encontraba apagado.',
    '3/11/2022,2013,Sin comunicación,Equipo sin comunicación,Sí,Se cambio radiomodem por problema de comunicación.,',
    '9/29/2022,2013,Sin comunicación,Placa RTU sin comunicación,Sí,Se reemplazo placa,no aplica',
    '10/11/2022,2013,Sin comunicación,Placa RTU sin comunicación,Sí,Se reemplazo placa RTU.,no aplica.',
    '3/2/2022,La Invernada,Otros,No se ejecutan los comandos.,No,Se observa que no llega tensión de comando desde la caja de control FXA hasta el gabinete RTU.,Se da aviso a personal de Equipo Eléctrico',
    '3/2/2022,2757,Alarma,Alimentacion de 220Vca Ausente,Sí,Se cambio placa de control dañada,',
    '10/20/2022,2030,Sin comunicación,Este es uno de los equipos que se encuentra sin comunicación pertenecientes a la BASE CON-TELGECS,No,Se realizaron diversas pruebas pero no se logra a una solucion,no aplica',
    '3/3/2022,2329,Preventivo,,Sí,,',
    '3/4/2022,797,Mala comunicación,errores de comunicación,Sí,Se cambio radiomdem,',
    '3/4/2022,Der. A Raco,Mala comunicación,antena mal orientada.,Sí,Se reoriento antena.,',
    '10/24/2022,2030,Sin comunicación,A determinar,Sí,Se cambio canal de comunicación,no aplica',
    '3/14/2022,2092,Sin comunicación,Registrador sin comunicación.,Sí,Se cambio radiomodem por problema de comunicación.,',
    '2/8/2022,2120,Sin comunicación,Indica Ausencia de 220.,Sí,Se cambio placa de control,',
    '12/28/2022,2228,Sin comunicación,radiomodem con falla,Sí,Se reemplazó radiomodem.,No aplica',
    '9/29/2022,2260,Sin comunicación,Placas de encendido y proteccion dañadas,Sí,Se reemplazaron placas,no aplica',
    '10/4/2022,2260,Sin comunicación,Placas de encendido y proteccion dañadas,Sí,Se reemplazaron placas,Las placas fueron dañadas por sobretensión en la Fase R.',
    '3/8/2022,2611,Preventivo,,,,',
    '10/6/2022,2260,Sin comunicación,Placas de encendido y proteccion dañadas,Sí,Se reemplazaron placas,Se realizo visita del sitio por tercera ves en los ultimos 7 días y siempre presemto la misma falla. Sobretension en la Fase R. Seria conveniente revisar dicha fase.',
    '10/26/2022,2260,Sin comunicación,Placas de encendido dañada,Sí,Se reemplazo placa de encendido,Se trabajo en conjunto cn personal de Adm. BRS para detectar un el motivo por el cual en esta SET se queman reiteradas veces las placas de proteccción y encendido en la fase R. No se encontro ningun desperfecto en el gabienete de Punto fijo en caja de proteccion.',
    '5/27/2022,2286,Sin comunicación,"Linea de vista obstruida, antena con elemento dañado. ",Sí,Se reemplazo antena,No se pudo instalar la antena en otro punto ya que la manposteria de la cabina no lo permite.',
    '3/10/2022,Auditoria Interna. No se realiza servicio,,,,,',
    '2/2/2022,2294,Sin comunicación,Placade encendido y placa de control dañadas,Sí,Se cambio placa de encendido y placa de control dañadas.,',
    '4/19/2022,2294,Sin comunicación,Radiomodem apagada,Sí,Se reemplazo radiomodem,',
    '11/22/2022,2294,Sin comunicación,Placa de Proteccion dañada,Sí,Se reemplazo placa de proteccion y bornera verde enchufable correspondiente a las tensiones.,Se encontro hormigas dentro de la caja de protección.',
    '9/5/2022,2317,Sin comunicación,Placa rtu y registrador sin comunicación,Sí,Fusible quemado en placa RTU. Se reemplaza placa.,no aplica',
    '11/11/2022,2317,Sin comunicación,Sin comunicación placa RTU y Registrador.,Sí,Se reemplazo placa RTU.,"El lugar geográfico donde se encuentra esta SET no permite una buena comunicación. Se recomienda, si esta dentro de las posibilidades, realizar el traslado del punto fijo a otra SET. "',
    '3/17/2022,2329,Sin comunicación,Equipo sin comunicación,Sí,,',
    '12/28/2022,2379,Sin comunicación,radiomodem con falla,Sí,Se reemplazó radiomodem.,No aplica',
    '10/19/2022,2412,Sin comunicación,Este es uno de los equipos que se encuentra sin comunicación pertenecientes a la BASE CON-TELGECS,No,Se realizaron diversas pruebas pero no se logra a una solucion,no aplica',
    '10/24/2022,2412,Sin comunicación,A determinar,Sí,Se cambio canal de comunicación,no aplica.',
    '3/15/2022,3505,Preventivo,,,,',
    '3/15/2022,2381,Preventivo,,,,',
    '3/15/2022,2379,Preventivo,,,,',
    '11/3/2022,2412,Sin comunicación,Antena dañada,Sí,Se cambio antena y cable coaxial. Tambien se reemplazo placa de protección por tener Alarma de ausencia de 220vca,El registrador indica Tensión de fase R = 210Vca',
    '8/12/2022,2464,Sin comunicación,RTU sin comunicación. Placa sulfatada.,Sí,Se reemplazó placa de RTU.,',
    '5/2/2022,2551,Sin comunicación,Radiomodem con mal funcionamiento.,Sí,Se reemplazo radiomodem,',
    '3/16/2022,4166,Preventivo,,,,',
    '6/29/2022,2717,Sin comunicación,Registrador sin comunicación,No,Al llegar al sitio se encontro registrador apagado. Al reiniciarlo luego de la presentacion inicial entrega un error en pantalla,Se da aviso a personal de Adm Concepción.',
    '4/18/2022,2728,Sin comunicación,Placa de control dañada.,Sí,Se reemplazo placa de control.,',
    '2/7/2022,2800,Sin comunicación,Radiomodem con mal funcionaiento.,Sí,Se reemplazo radiomodem,',
    '11/8/2022,2846,Sin comunicación,Antena y cable coaxial dañados,Sí,Se reemplazo cable coaxial y antena.,no aplica.',
    '4/7/2022,2927,Sin comunicación,Radiomodem no enciende,No,Trabajando en el sitio se nos imposibilita ingresar al sistema SCADA. Nos avisan desde Noanet que realizaran mantenimiento en los sevidores hasta las 17:00 hs. Se trae radiomdem para ser revisada en Digicom.,',
    '3/18/2022,7421,Preventivo,Equipo preventivo,,,',
    '4/18/2022,2927,Sin comunicación,Radiomodem no enciende,Sí,Se cambio radiomodem,Se terminó con tarea inconclusa del día 7/4/22',
    '3/18/2022,7884,Preventivo,,,,',
    '3/21/2022,La Rural,Mala comunicación,No se tiene buena linea de vista hacia la base de comunicación,Sí,Se comunico por el canal de Tafi Viejo usando como repetidora el radiomodem de CM Los Cebiles,',
    '3/21/2022,Los Cebiles,Otros,ninguno,Sí,Se reconfiguro radiomodem como repetidora para CM La Rural,',
    '2/23/2022,2982,Sin comunicación,Registrador sin comunicación,Sí,se reemplazo cambio placa de encendido y protección,',
    '11/23/2022,2992,Sin comunicación,Placa de protección dañada,Sí,Se reemplazo placa de protección,Se encontro panal de avispas dentro de la caja de protección. Se normalizo conexiónes del registrador.',
    '3/22/2022,Previsión A (CAM),Mala comunicación,Errores de comunicación intermitentes,No,No nos permitieron ingresar al edificio de prevision social por motivos internos. Queda previsto regresar.,',
    '3/22/2022,2560,Preventivo,,,,',
    '3/22/2022,722,Preventivo,,,,',
    '3/22/2022,1141,Preventivo,,,,',
    '3/22/2022,Anill. San Javier Ohuanta,Preventivo,,,Se trae RTU a Digicom para realizarle un mantenimento preventivo ya que se solicito ponerlo en servicio el día miércoles 30/03.,',
    '9/16/2022,3091,Sin comunicación,Registrador sin comunicación,Sí,se reemplazo batería de 12vcc,no aplica',
    '4/28/2022,3093,Sin comunicación,Placa de proteccion y radiomodem dañados,Sí,Se reemplazo placa de protección y radiomodem dañados.,Se quito panal de avispas dentro del gabinete de Punto Fijo y Protección.',
    '3/23/2022,Tafi Viejo,Alarma,Alarmas de ausencia de Alimentación de 220Vca General.,,Personal de Edet en el sitio nos informa que todo se encuentra normal y corroboraron la presencia de alimentación de 220Vca en el rebaje. Ya en el lugar se verifica que no esta llegando tensión de 220Vca desde el transformadpor de Servicos auxiliares.,',
    '2/24/2022,3096,Sin comunicación,Fusibles quemados en placa de encendido y placa de protección.,Sí,Se cambiaron fusibles quemados de las respectivas placas,Se normalizaron conexiones del registrador.',
    '3/25/2022,Raco,Otros,,,se asesoró a guardia de EDET en la ejecución de maniobras a pie de equipo desde el gabinete RTU. Se puso en servicio el Distribuidor El Siambon.,',
    '3/28/2022,La Comuna,Otros,tensión de señaizacion de 110Vca,Sí,Se cambio la tension de señalizacion de 110Vca a 12Vcc.,Se probo el comando de recierre y se comprobo que sale del gabinete RTU pero no cambia el estado en la Caja de Control.',
    '3/21/2022,3096,Sin comunicación,Placa de protección dañada,Sí,Se reemplazo placa de protección dañada.,Se normalizaron conexiones del registrador.',
    '1/19/2022,3134,Sin comunicación,Placa de protección dañada.,Sí,Se cambió placa de protección.,Se corrigió conexiones de alimentación de registrador.',
    '3/29/2022,Ave. Aerea.,Alarma,Mala señalización del estdo del reconectador,Sí,Al llegar al sitio se observa que el mismo esta abierto como lo indica la señalización en SCADA y con bypass puesto. Se realizan pruebas de telecomando y señalización observando que la caja de control FXA no responde.,',
    '1/25/2022,3159,Sin comunicación,Registrdor sin comunicación,Sí,Se ajustaron cable de comunicación sueltos en borneras del registrador.,',
    '3/29/2022,3172,Sin comunicación,Registrador sin comunicación.,Sí,Se reparo placa de encendido dañada.,Se encontrarom hormigas dentro del gabinete de punto fijo. Se normalizo conexiones del registrador.',
    '11/24/2022,3197,Sin comunicación,Placa de control dañada,Sí,Se reemplazo placa de control.,no aplica.',
    '6/2/2022,3250,Sin comunicación,Cable coaxial dañado.,Sí,Se reemplazo cable coaxial,',
    '11/3/2022,3250,Sin comunicación,A determinar,Sí,Se cambio canal de comunicación,no aplica',
    '3/31/2022,2244,Alarma,Alarma de Local,Sí,Se cambio placa de control.,',
    '11/10/2022,3257,Sin comunicación,Potencia Reflejada con niveles elevados,Sí,Se reemplazo antena,no aplica',
    '3/3/2022,3319,Sin comunicación,Registrador sin comunicación,Sí,Se reemplazo placa de encendido dañada.,Se normalizo conexiones del registrador.',
    '4/4/2022,4714,Alarma,alarma de Tensión de RTU superior al máximo,Sí,Se reemplazo placa RTU dañada,',
    '3/17/2022,3319,Sin comunicación,Equipo sin comunicación,Sí,,',
    '3/17/2022,3324,Sin comunicación,Equipo sin comunicación,Sí,,',
    '4/5/2022,1173,Mala comunicación,Antena en mal estado.,Sí,Se cambio antena y se reemplazo batería agotada,No aplica',
    '11/24/2022,3389,Sin comunicación,Placa de control dañada,Sí,Se reemplazo placa de control.,Se cambio batería por estar agotada y se reemplazo radiomodem por tener potencia reflejada con niveles elevados.',
    '4/6/2022,3922,Mala comunicación,Placa de control dañada.,Sí,Se reemplazo placa de control,',
    '4/22/2022,3529,Sin comunicación,Placa de protección y placa de control dañadas.,Sí,Se reemplazaron placas de protección y de control.,Caja de protección y gabinete punto fijo con avispas. Se normalizo conexiones del registrador.',
    '6/24/2022,3685,Sin comunicación,Radiomodem apagada,Sí,Se cambio placa de control.,',
    '7/26/2022,3685,Sin comunicación,"Placa de control dañada, no entrega alimentación de Vcc",Sí,Se reemplazo placa de control.,',
    '2/2/2022,3846,Sin comunicación,Registrador sin comunicación,Sí,Se apago el regsitrador y volvio a encender registrtador y le vanto la comunicación .,Registrador con mal funcionamiento.',
    '4/11/2022,Trapani,Otros,Sin lectura las señales del los distribuidores.,Sí,Se reemplazo placa ED-28,El Rec de entrada se encuentra con placas dañadas dentro de la caja de control.',
    '4/11/2022,786,Preventivo,Preventivo.,Sí,Se suspende tarea por lluvia.,',
    '4/12/2022,Trapani,Otros,Sin lectura las señales del los distribuidores.,Sí,Se encontraron fusibles quemados en caja de control de los distribuidores. Se realizaron pruebas de telecomando y se detecto que la placa de comando presenta alguna falla. Se desmonta placa para ser revisada en Digicom.,',
    '11/2/2022,4050,Sin comunicación,Placa de encendido dañada,Sí,Se reemplazo placa de encendido,Se normalizo conexiones del registrador.',
    '4/12/2022,2092,Otros,El registrador no genera los registros correctos.,Sí,Se reconfiguro registrador. Se soluciono problema de alarma de ausencia de 220vca cambiando laca de control.,queda configurado con TI 250/5',
    '4/12/2022,2208,Preventivo,Preventivo.,,,',
    '4/13/2022,Trapani,Otros,No se realizan los telecomandos.,Sí,Se reemplazo placa RTU de control. Y se instaló placa de comando que se quitaron el 12/4.,',
    '7/18/2022,4152,Sin comunicación,A determinar,Sí,Se cambio canal de comunicación por V. Nogues C1,',
    '9/19/2022,4231,Sin comunicación,A determinar,No,no se pudo determinar el motivo de la falta de comunicación. Se verificaron que todas las configuraciones del firmware y los niveles de tensiones sean los correctos.,Se regresara al sitio a dar solución.',
    '2/23/2022,4281,Sin comunicación,A determinar,No,No se pudo ingresar al sitio por estar en una propiedad privada.,',
    '4/14/2022,Ciudacita,Sin lectura,Llave térmica actuada en caja de protección y placa quemada en caja de control FXA,No,Se da aviso por mail a COD y Equipo Eléctrico del estado de la caja de control.,',
    '3/16/2022,4281,Sin comunicación,Registrador sin comunicación,Sí,Se reconfiguro velocidad de comunicación del registrador.,',
    '3/23/2022,4281,Sin comunicación,Equipo sin comunicación,Sí,Se trabajo en el sitio pero no se pudo probar los resultados de las tareas realizadas ya que el canal de comunicación Base Los Ralos se encontraba sin funcionar debido a que personal de Noanet estaba realizando trabajos sobre dicha base.,',
    '3/30/2022,4281,Sin comunicación,Radiomodem con mal funcionaiento.,Sí,Se reemplazo radiomodem,',
    '4/18/2022,Las Talitas,Sin lectura,Luego de realizar un telecomando sobre el rec de entrada se quedaron sin lectura los reconectadores,Sí,Se repuso placa multipuerto dañada.,Se averio transformador de potencia del rebaje',
    '5/2/2022,4281,Sin comunicación,Radiomodem con mal funcionamiento.,Sí,Se reemplazo radiomodem,',
    '4/19/2022,Las Talitas,Otros,Se averio transformador de potencia del rebaje,Sí,Nos solicitan estar presentes en pruebas de telecontrol previas a la puesta en servicio del nuevo transformador. Las pruebas salieron correctas.,',
    '4/26/2022,4376,Sin comunicación,Registrador sin comunicación.,Sí,Se reemplazo cable de comunicación del registrador por estar cortado.,',
    '6/28/2022,4376,Sin comunicación,error de comunicación,Sí,Se reemplazo batería dañada.,',
    '5/30/2022,4538,Sin comunicación,Placa de control no entrega alimentación de continua,Sí,Se reemplazo placa de control.,',
    '2/1/2022,4572,Sin comunicación,Registrador sin comunicación,Sí,Se cambio placa de protección y se normalizo conexiones del registrador.,',
    '4/21/2022,La Invernada,Otros,No se ejecutan los comandos.,No,No llega tensión de comando (36Vcc) desde la caja de control FXA hasta el gabinete RTU.,Este reconectador fue visitado e informado por el mismo problema el 2/3/22.',
    '4/21/2022,Concepción - TELGECS,Preventivo,,,,',
    '4/20/2022,4572,Sin comunicación,Registrador sin comunicación.,Sí,Se reconfiguro velocidad de comunicación del registrador.,',
    '4/21/2022,Santa Lucia,Otros,No se ejecutan los comandos.,Sí,"al llegar al sitio se encontro personal de EDET trabajando en el cambio de unos descargadores, al finalizar se realizaron pruebas de telecomando exitosas. ",',
    '9/19/2022,4572,Sin comunicación,Registrador sin comunicación.,Sí,Se reconfiguro velocidad de comunicación del registrador.,Este registrador debe estr con figurado a veocidad 9600 Baud.',
    '4/21/2022,4611,Sin comunicación,Radiomodem con mal funcionamiento.,Sí,Se reemplazo radiomodem,',
    '12/27/2022,4611,Sin comunicación,Sin comunicación RTU y registrador,Sí,Se reemplazó RTU y se configuró registrador,No aplica',
    '4/4/2022,4618,Sin comunicación,Placa de protección dañada,Sí,Se reemplazo placa de protección.,',
    '4/4/2022,4622,Sin comunicación,Placa de control dañada.,Sí,Se reemplazo placa de control.,',
    '4/28/2022,4622,Sin comunicación,Placa RTU y de control dañadas.,Sí,Se reemplazo placas de control y protección.,Se normalizo conexiones del registrador.',
    '4/25/2022,Avellaneda Aerea,Sin lectura,Al cerrar el reconectador queda sin lectura el estado del mismo.,Sí,Se realizaron pruebas de telecomando y la señaizacion fue correcta.,',
    '3/21/2022,4628,Sin comunicación,Equipo sin comunicación,,No se pudo llegar al sitio por el mal estado de los caminos.,',
    '4/6/2022,4628,Sin comunicación,Placa de protección dañada,Sí,Se reemplazo placa de protección.,',
    '3/23/2022,4630,Sin comunicación,Placa de proteccion dañada,Sí,Se reemplazo placa de proteccion dañada.,Se encontro panal de avispas dentro del gabinete.',
    '3/30/2022,4630,Sin comunicación,antena mal orientada,Sí,Se reoriento antena.,',
    '12/5/2022,4630,Sin comunicación,Caja de protección dañada,Sí,"Se reemplazo chapa completa (chapa, borneras fronteras, cables, placa, borneras enchufables) de la caja de protección.",se saco panal de avispas de dentro de la caja de protección.',
    '10/3/2022,4729,Sin comunicación,radiomodem con mal funcionamiento.,Sí,se reemplazo radiomodem,no aplica',
    '3/31/2022,4818,Sin comunicación,Placa de protección dañada,No,No se pudo trabajar en el sitio debido a camiones estacionados impedian colocar la escalera. Queda pendiente regresar.,',
    '4/6/2022,4818,Sin comunicación,Placa de encendido dañada,Sí,Se reemplazo placa de encendido,',
    '5/31/2022,4818,Sin comunicación,Bornera encufable de la entrada de la placa de proteccion dañada,Sí,Se reemplazo bornera.,Se normalizo conexiones del registrador.',
    '4/28/2022,Lules,Otros,Registrador desconfigurado,Sí,Se reconfigura registrador,',
    '1/3/2022,4875,Sin comunicación,No se comunicaba ningun elemento,Sí,Se cambio canal de comuniacion por Villa Nogues C1.,',
    '2/18/2022,5994,Sin comunicación,Equipo sin comunicación,Sí,se cambio radiomodem por problema de comunicación.,',
    '6/29/2022,6138,Sin comunicación,error de comunicación,Sí,Se reemplazo radiomodem,',
    '4/29/2022,6365,Sin comunicación,Registrador sin comunicación,Sí,Se reconfiguro velocidad de comunicación del registrador.,',
    '5/31/2022,6436,Sin comunicación,Placa de control dañada.,Sí,Se reemplazo placa de control.,',
    '4/29/2022,3250,Mala comunicación,Antena mal orientada,Sí,Se reoriento antena.,',
    '9/30/2022,6442,Sin comunicación,Placa de control dañada,Sí,Se reemplazo placa de control,También se soluciono alarma de ausencia de 220Vca.',
    '1/27/2022,6663,Sin comunicación,Placa de control dañada.,Sí,Se reemplazo placa de control,',
    '5/4/2022,6860,Sin comunicación,Placa de control dañada.,Sí,Se reemplazo placa de control,',
    '5/2/2022,617,Mala comunicación,Antena Dañada,No,Se observa antena dañada con cables con tension que pasan por la misma que imposibilita cambiarla.,Se debe realizar un corte para poder acceder hasta la antena.',
    '7/19/2022,6860,Sin comunicación,A determinar,Sí,Se reemplazo radiomodem,Gabinete de Punto fijo sin PAT. Durante la tarea no se pudo conectar la PAT ya que el unico punto de vinculación se encuentra cerca del transformador.',
    '5/3/2022,Avell. Aerea,Otros,Estado del reconectador sin estados.,Sí,Se cambio placa RTU y se cambio tensión de señalización para 12Vcc.,',
    '2/22/2022,7079,Sin comunicación,Equipo sin comunicación,Sí,Se reemplazo placa de control dañada.,',
    '5/3/2022,2224,Mala comunicación,Se imposibilita reorientar la antena por la presencia de lineas con tensión.,Sí,Se cambia de canal de cmunicaciones por la Base V. Nogues C2.,',
    '5/4/2022,Los Aguirres,Alarma,Alarma intermitente de Alimentación ausente.,,,',
    '5/4/2022,1554,Mala comunicación,Errores de comunicación intermitentes,Sí,Se reemplazo radiomodem,',
    '4/13/2022,7079,Sin comunicación,Placa de control dañada.,Sí,Se reemplazo placa de control.,',
    '9/7/2022,7113,Sin comunicación,no aplica,Sí,Se reemplazaron radiomodem y placa de control.,no aplica',
    '5/6/2022,se llevo a reparar camioneta no se realiza servicio,,,,,',
    '5/9/2022,2286,Mala comunicación,Linea de vista obstruida,No,Se edifico un tinglado a la par de la antena que obstaculisa la linea de vista. Se analiza reubiar la antena.,',
    '6/28/2022,7197,Sin comunicación,Registrador sin comunicación,Sí,Se reconfiguro velocidad de comunicación del registrador.,',
    '5/9/2022,1512,Preventivo,,,,',
    '7/20/2022,7537,Sin comunicación,Placa RTU sin comunicación,Sí,Se reconfiguro placa RTU,',
    '5/10/2022,317,Otros,Se verifica funcionaiento del registrador.,Sí,se verifica el funcionamiento del registrados debido a un faltante de datos entre el 29/04 y el 01/05. Estando el el sitio se apago el registrador y el mismo no volvio a encender. Se verifico que el mismo tenia tensión de alimentación correcta.,Se recomendo cambiar el registrador.',
    '5/10/2022,Anill. San Javier Ohuanta,Otros,Sin comunicación.,No,Se instala fuente de alimentación para realizar pruebas de comandos en el día de mañana miércoles 11/05,',
    '5/11/2022,Anill. San Javier Ohuanta,Otros,Sin comunicación.,No,"Se instalan baterias nuevas y radiomodem, se realizan pruebas de comunicaciones correctas. No se realizan pruebas de telecontrol ya que la tarea se extendio mas alla del tiempo estimado del corte. ",Se debera coordinar una nueva tarea para realizar pruebas de telecomando.',
    '5/12/2022,Taco Ralo,Alarma,Alarma: ausencia de 220Vca,Sí,Se reemplazo placa de encendido dañada.,',
    '5/12/2022,7527,Preventivo,,,,',
    '5/13/2022,Del Este - TELGECS,Preventivo,,,,',
    '5/13/2022,Del Este - COD,Preventivo,,,,',
    '1/12/2022,7733,Sin comunicación,,Sí,,',
    '5/16/2022,696,Preventivo,,,,',
    '5/17/2022,1141,Alarma,Alarmas varias en RTU.,Sí,Se reemplazo placa de RTU dañada.,',
    '5/17/2022,2443,Preventivo,,,,',
    '5/17/2022,2531,Preventivo,,,,',
    '5/17/2022,3351,Preventivo,,,,',
    '5/17/2022,338,Preventivo,,,,',
    '5/17/2022,397,Preventivo,,,,',
    '11/9/2022,7733,Sin comunicación,Placa de control dañada,Sí,Se reemplazo placa de control.,Se reemplazo batería por estar dañada.',
    '5/19/2022,906,Preventivo,,,,',
    '5/19/2022,3749,Otros,,,Se realizo la desintalación del punto fijo en dicha set para reacondicionarlo e instalarlo el viernes 20/05 en la SET 8635,',
    '5/20/2022,8635,Otros,Ninguno,Sí,Se instalo el punto fijo desinstalado de la set 3749,',
    '1/17/2022,7989,Sin comunicación,Placa de control dañada.,Sí,Se reemplazó placa de control.,',
    '5/20/2022,2809,Preventivo,Equipo cerca de la linea de MT,No,No se realiza servicio preventivo ya que el gabinete de punto fijo no respeta distancia de seguridad.,',
    '5/20/2022,Peru N. y Reconquista,Preventivo,,,,',
    '5/23/2022,Las Pierdritas,Mala comunicación,Errores de comunicación intermitentes,Sí,Al llegar al sitio el equipo funciono correctamente. No se pudo determinar el posible problema.,',
    '5/23/2022,Hospital del Este,Alarma,Alarma: Secc PAT Reserva Cerrado,No,"se encuentran celdas con humedad en los micro-switch, por este motivo las señales que aparecen en SCADA no son reales. ",Se trabajo en conjunto a Equipo Eléctrico.',
    '5/23/2022,267,Alarma,Alarma: Ausencia de Fase.,Sí,Se reemplazo placa de proteccion dañada.,',
    '5/23/2022,1925,Preventivo,,,,',
    '5/23/2022,9288,Preventivo,,,,',
    '1/25/2022,8106,Sin comunicación,Placa de control dañada.,Sí,Se cambio placa de control.,',
    '1/28/2022,8424,Sin comunicación,Equipo sin comunicación,Sí,Se cambio placa de control dañada,',
    '5/10/2022,9359,Sin comunicación,Cable coaxial dañado.,Sí,Se reemplazo cable coaxial y se reconfiguro velocidad del registrador.,',
    '11/29/2022,9359,Sin comunicación,Registrador sin comunicación,Sí,Se reconfiguro velocidad de comunicación del registrador.,Debe estar configurado a 9600Baud.',
    '5/26/2022,639,Preventivo,,,,',
    '5/26/2022,980,Preventivo,,,,',
    '12/27/2022,9359,Sin comunicación,Registrador sin comunicación,Sí,Se reconfiguro velocidad de comunicación del registrador.,Se configuroó a 9600 Baud.',
    '5/27/2022,Villa Nogues,Preventivo,ninguno,,Se verifico e buen estado de la fuente y del banco de baterías.,',
    '6/1/2022,9645,Sin comunicación,manguera de tensiones y corrriente dañada,Sí,Se reemplazo manguera y conector circular,',
    '1/11/2022,9731,Sin comunicación,No se comunicaba ningun elemento,Sí,Placa de control dañada. Se reemplazo placa,Se corrigio conexiones de alimentacion de registrador.',
    '2/4/2022,9731,Sin comunicación,Placa de protección dañada.,Sí,Se cambio placa de protección y se normalizo conexiones del registrador.,',
    '3/16/2022,9731,Sin comunicación,Equipo sin comunicación,Sí,Se reemplazo placa de proteccion dañada.,Se normalizaron conexiónes del registrador',
    '4/22/2022,9757,Sin comunicación,Placa de proteccion dañada,Sí,Se reemplazo placa de protección.,Se normalizo conexiones del registrador.',
    '5/31/2022,Las Tranquitas,Preventivo,,,,',
    '5/31/2022,3541,Preventivo,,,,',
    '6/1/2022,Cuesta del 25,Otros,ninguno,Sí,se solicito la presencia de personal de Digicom en el sitio para verificar si el trabajo afectaba a los equipos de comunicación en la zona.,',
    '6/1/2022,Colonia 1,Otros,El reconectador quedo sin comunicación durante las 7:50 Hs y 8:50 Hs debido al desenganche del Distr. Ranchillo,Sí,Se reemplazo batería dañada.,La batería dañada fuen instalada en septiembre de 2021',
    '9/30/2022,9757,Sin comunicación,Cable coaxial dañado.,Sí,Se reemplazo cable coaxial,no aplica',
    '6/2/2022,191,Preventivo,,,,',
    '1/18/2022,9769,Sin comunicación,Indica Ausencia de 220 y Falta de Fase.,No,se encuentra en perfectas condiciones el equipo de telemedición- No tiene alimentacion de Vca.,No llegan 220 Vca a la placa de protección. Se avisó al Ing. Sebastián Ahumada.',
    '6/2/2022,3264,Preventivo,,,,',
    '6/2/2022,8022,Preventivo,,,,',
    '6/3/2022,6060,Otros,No se puede bajar datos a pie de equipo.,Sí,Se ajustaron cables de comunicación en borneras del registrador.,',
    '11/23/2022,9769,Sin comunicación,Placa de protección dañada,Sí,Se reemplazo placa de protección y bornera verde encufable correspondiente a las tensiones.,Se encontro panal de avispas dentro de la caja de protección. Se normalizo conexiónes del registrador.',
    '12/7/2022,9854,Sin comunicación,Placa de Proteccion y endendido dañadas,Sí,Se reemplazaron placas.,La placa de protección se encontraba dañada en el circuito de la fase R.',
    '6/6/2022,3389,Preventivo,,,,',
    '6/6/2022,3244,Mala comunicación,Cable coaxial dañado.,Sí,Se reemplazo cable coaxial.,Se soluciona la Alarma de ausencia de fase reemplazando placa de control.',
    '6/7/2022,Mariño,Sin lectura,Fines de carrera entregan el mismo estado,No,Ambos fines de carrera se encontraban cerrado por lo tanto se de deberon verificar los mismos.,',
    '6/7/2022,Ricchio,Mala comunicación,Los equipos que se comunican atraves de esta repetidora poseen mala comunicación,No,Se cambio radiomodem y se reoriento antena pero no se logro mejorar la comunicación. Queda pendiente regresar al sitio.,',
    '6/7/2022,36,Preventivo,,,,',
    '6/7/2022,823,Preventivo,,,,',
    '6/7/2022,437,Preventivo,,,,',
    '6/8/2022,Mariño,Otros,Señalización del estado del Secc. Invertida.,Sí,Se invirtieron los cables provenientes de los fines de carrera.,Cuando el SBC se encontraba abierto señalizaba cerrado en el sistema SCADA.',
    '6/8/2022,La Trinidad,Mala comunicación,Distribuidor Santa Rita con errores de comunicación intermitetes.,Sí,Se reemplazo intergrado de comunicación RS 485 defectuoso en placa RTU de Control.,',
    '4/22/2022,,Sin comunicación,Falso contacto en alimentación de radiomodem,Sí,Se reemplazo radiomodem,',
    '9/12/2022,7989 GPRS,Sin comunicación,Sin comunicación con analizador,Sí,Se cambió velocidad del analizador.,no aplica',
    '6/9/2022,1185,Preventivo,,,,',
    '6/9/2022,1192,Preventivo,,,,',
    '6/9/2022,1460,Preventivo,,,,',
    '6/10/2022,3827,Preventivo,,,,',
    '6/10/2022,1651,Preventivo,,,,',
    '6/10/2022,3656,Preventivo,,,,',
    '6/13/2022,Arr. Reb. Camino del Peru,Preventivo,,,,',
    '6/13/2022,Los Nogales,Preventivo,,,,',
    '6/13/2022,Radio Nacional,Preventivo,,,,',
    '6/13/2022,Contitución y Ruta 9,Preventivo,,,,',
    '6/13/2022,El Arsenal,Preventivo,,,,',
    '1/12/2022,Agua Dulce 2,Sin comunicación,No existe Buena linea de vista con la base de comunicación actual.,Sí,Se cambio canal de comunicación,',
    '6/14/2022,Comisaría,Preventivo,,,,',
    '4/14/2022,Alberdi,Sin comunicación,Radiomodem con mal funcionamiento.,Sí,Se cambio radiomodem,',
    '6/14/2022,2811,Preventivo,,,,',
    '6/15/2022,Amaicha - TELGECS,Otros,Medición  de Corrientes del Distr. Encalilla en 0 amp.,No,Se verificó la correcta configuración y conexiones en el registrador. Se midio a las salidas de los TI el valor de 0 amp en las tres fases. Se concluye que el registrador funciona correctamente.,',
    '6/15/2022,Amaicha - Operaciones,Preventivo,,,,',
    '6/15/2022,Ampimpa - Operaciones,Otros,Caja de protección dañada,Sí,Se reemplazo caja de protección,',
    '6/15/2022,Ampimpa - TELGECS,Otros,Caja de protección dañada,Sí,Se reemplazo caja de protección,',
    '9/20/2022,Amaicha,Sin comunicación,Llave termica de Uca Rectifcador Actuada,Sí,"Se normalizo llave termica y se verifico el buen estado del banco de baterias de 24Vca, se cambio bateria de 12Vcc 12Ah. ",no aplica',
    '6/16/2022,Ricchio,Otros,Los equipos que se comunican atraves de esta repetidora poseen mala comunicación,Sí,Se reemplazo antena,',
    '6/16/2022,Lules,Mala comunicación,Errores de comunicación intermitentes,No,No se logro ingresar al rebaje ya que no habia personal disponible para retirar la llave de la sucursal.,',
    '6/21/2022,Bracho,Otros,Potencia Activa de la Fase L2 indica 0 W.,Sí,,',
    '3/17/2022,Amaicha - Operaciones,Sin comunicación,Equipo sin comunicación,Sí,,',
    '6/21/2022,Lules,Mala comunicación,Errores de comunicación intermitentes,Sí,Se reemplazo radiomodem,',
    '1/10/2022,Ampimpa,Sin comunicación,Fuente de alimentación dañada.,Sí,Se cambio fuente de alimentacion,',
    '1/26/2022,Ampimpa - TELGECS,Sin comunicación,No llega alimentacion de 220Vca a gabinete de repetidora proteccion dañada,Sí,Se reparo placa de proteccion. Se debe regresara reemplazar el gabinete de proteccion por estar dañado.,',
    '3/30/2022,Anill. San Javier Ohuanta,Sin comunicación,equipo sin comunicación,No,Se trabaja en conjunto con personal de administracion monteros acondicionando el SBC para que entre en funcionamiento. Se suspende tarea quedando inconclusa por la lluvia.,Se debe reemplazar y cambiar la posición de los fines de carrera.',
    '6/23/2022,Villa Nogues Rebajes,Preventivo,se visita base ya que algunos equipos que se comunican atraves de ella presentan mala comunicación,Sí,Se reemplazo Radiomodem,',
    '6/16/2022,Anill. San Javier Ohuanta,Sin comunicación,sin comunicación,Sí,Se continua con tarea pendiente del 11/05. No se ejecutan los comandos. Se desmonta caja de control completa para controlarla en Digicom,',
    '12/21/2022,Arr. San Javier,Sin comunicación,Alimentacion de 220Vca Ausente,Sí,Al legar al sitio se encuntra el equuipo funcionando corectamente,"Se realizaron pruebas de Señalización: Supervisión, Recierre y Alimentación. "',
    '3/8/2022,Avellaneda A y B - CAM,Sin comunicación, Sin alimentación de 220Vca en el gabinete de las Bases.,Sí,Se normaliza llave térmica actuada en tablero General.,',
    '5/26/2022,Ayacucho,Sin comunicación,Medidor del Alimentador N°4 sin comunicación,No,Medidor apagado. Si llega tensión de alimentación pero no enciende.,',
    '10/6/2022,B° Soeme,Sin comunicación,radiomodem desconfigurada,Sí,Se reconfiguro radiomodem.,No solicitaron visitar el sitio ya que esta caja de control fue reistaladas en estos ultimos dias y no se logro levantar las comunicaciones.',
    '6/24/2022,Malvinas,Mala comunicación,Sin linea de vista,No,Se suspende tarea ya que no se puede colocar escalera debido a vehículos estacionados en la zona del poste.,Se regreso por la tarde y los vehículos aun se encontraban en el lugar.',
    '6/24/2022,1265,Preventivo,,,,',
    '6/24/2022,2193,Preventivo,,,,',
    '6/27/2022,Malvinas,Mala comunicación,radiomodem con falla,Sí,Se reemplazo radiomodem.,',
    '6/27/2022,42,Preventivo,,,,',
    '6/27/2022,Fortunata García,Otros,Comando de cierre.,No,"Con personal de Digicom en el sitio se realizaron telecomando desde el COD. Al mandar un comando de cierre se verifica en el lugar que el rec cierra y automáticamente se vuelve abrir, luego actúa el recierre pero nuevamente se vuelve a abrir.",Se da aviso a personal de Equipo Eléctrico',
    '6/27/2022,Agua Dulce 2,Mala comunicación,radiomodem con falla,Sí,Se reemplazo radiomodem,',
    '6/27/2022,árbol Solo,Preventivo,,,,',
    '6/28/2022,Fortunata García,Otros,Telecontrol,Sí,Se realizan pruebas de telecontrol conjuntamente con equipo eléctrico con resultado correcto,',
    '12/22/2022,Banda Rio Sali - COD,Sin comunicación,Switch de NOANET apagado,Sí,A llegar al sitio se verifico que los Equipos de DIGICOM funcionaban correctamente. Personal de NOANET reseteo multitoma de alimentacion de los Swicht.,No aplica',
    '10/27/2022,Barrio Congreso,Sin comunicación,Placa de encendido dañado.,,,',
    '6/28/2022,S. Martin y S. Luis,Mala comunicación,Alarma de ausencia de 220Vca,No,Al llegar al sitio se encontro llave térmica actuada en caja de protección y se observan cables quemados en placa de protección.,',
    '3/29/2022,Barrio Soeme,Sin comunicación,La caja de control del reconectador no se encuentra en el sitio.,No,Se visito el sitio por el error de comunicación previamente consultando al COD de novedades al respecto. Al llegar al sitio se observa que laaja de control fue desmontada.,',
    '8/30/2022,Bo. Congreso,Sin comunicación,Placa de protección y placa de encendido quemadas,No,,se indica a COD de la situación de la caja de control para que sea revisada.',
    '2/8/2022,Bracho,Sin comunicación,Registrador sin comunicación,No,Llega alimentacion de 110Vca pero el registrador no enciende.,Analizador aparentemente quemado.',
    '2/11/2022,Bracho,Sin comunicación,Registrador sin comunicación,No,no se reemplaza registrador ya que el repuesto no es el indicado por los niveles de tensión de alimentación,Se coordina una visita el día Lunes para reenplazar el registrador.',
    '6/30/2022,San Pedro - COD,Otros,Instlación,Sí,Se instalo repetidora COD para comunicar Nuevo Rebaje San Pedro.,',
    '7/1/2022,Castoral,Sin lectura,Sin lectura distribuidores y Rec de entrada,Sí,Se reemplazo placa multipuerto.,',
    '7/1/2022,Der. A Mista,Otros,Se revisa reconectador ya que la guardia de de Santa Rosa nos indica que no se ejecutan telecomandos.,Sí,Desde sistema SCADA se verifica buena comunicación y señalización correcta. Se verifico que los comandos salieran desde el gabinete RTU. Se verifico buen estado de las baterías.,Queda pendiente verificar que los comandos de apertura y cierre se ejecuten correctamente sobre el reconectador.',
    '7/1/2022,3080,Preventivo,,,,',
    '7/1/2022,4198,Preventivo,,,,',
    '7/1/2022,6417,Preventivo,,,,',
    '2/15/2022,Bracho,Sin comunicación,Registrador sin comunicación,Sí,Se instala registrador nuevo,',
    '7/4/2022,459,Mala comunicación,Antena mal orientada,Sí,Se reoriento antena y se ajusto ya que estaba suelta.,',
    '7/4/2022,1891,Preventivo,,,,',
    '7/4/2022,6236,Preventivo,,,,',
    '7/4/2022,670,Preventivo,,,,',
    '7/5/2022,1550,Preventivo,,,,',
    '7/5/2022,725,Preventivo,,,,',
    '7/5/2022,424,Preventivo,,,,',
    '4/29/2022,Burruyacu,Sin comunicación,Reconectadores sin comunicación,Sí,Se reemplazo placa multipuerdo dañada.,',
    '1/27/2022,C. del 25 - Operaciones,Sin comunicación,Sin comunicación desde el 26/1 a las 14:30,No,Enlaces de Noanet dañados.,',
    '7/6/2022,S. Martin y S. Luis,Mala comunicación,A determinar,No,"Se debe verificar estado de antena y cable coaxial, no es posible realizarlo por la proximidad a la LMT. ",Se debe realizar un corte y utilizar una barquilla para poder acceder hasta la antena por la altura a la que esta instalada.',
    '7/6/2022,Solano Vera,Preventivo,,,,',
    '7/7/2022,Anill. San Javier Ohuanta,Otros,Instalación de caja de control reacondicionada,Sí,se suspende tarea por mal tiempo.,',
    '7/7/2022,,Preventivo,,,,',
    '7/7/2022,1916,Preventivo,,,,',
    '7/7/2022,2978,Preventivo,,,,Gabinete de Punto fijo sin PAT. Durante la tarea no se pudo conectar la PAT ya que el unico punto de vinculación se encuentra cerca del transformador.',
    '1/27/2022,C. del 25 - TELGECS,Sin comunicación,Sin comunicación desde el 26/1 a las 14:30,No,Enlaces de Noanet dañados.,',
    '7/8/2022,1791,Preventivo,,,,',
    '7/11/2022,Anill. San Javier Ohuanta,Otros,ninguno,Sí,Se instalo caja de control reacondicionada y se realizaron pruebas de telecontrol con resultados positivos.,',
    '1/3/2022,Camino del Peru,Sin comunicación,Todo el rebaje esta sin comuniacion,Sí,Se cambio cargador de batería y batería de 12Ah por estar dañados.,',
    '7/12/2022,7989,Preventivo,,,,',
    '7/12/2022,2160,Preventivo,,,,',
    '3/18/2022,Camino del Perú,Sin comunicación,Distribuidor Uttinger sin comunicación.,No,,El módulo de alimentación de la caja de comandos del reconectador se encontró dañado. Se avisa al COD y a Equipos Eléctricos.',
    '4/25/2022,Camino del Perú,Sin comunicación,Distribuidor Uttinger sin comunicación.,Sí,Luego de que fue reparada la caja de control del reconectador se procedio a conectar los cables de comunicación y se soluciono el problema.,',
    '7/13/2022,S. Martín y S. Luis,Mala comunicación,Linea de vista obstruida,Sí,Se cambio de posicion antena y se comunico atraves de la repetidora Ricchio,',
    '7/13/2022,Manantial,Sin lectura,Sin determinar,Sí,Al llegar al sitio el problema ya no estaba presente. Se realizo una inspección completa de las placas pero no se pudo determinar la posible causa.,',
    '10/13/2022,Camino del Perú,Sin comunicación,Medidor Roca Oeste sin comunicación,Sí,Se observa que e medidor entrega una respuestas de datos erroneas al sistema SCADA. El Medidor esta dañado.,Se verifico además que el Medidor Malvinas se encuentra con comunicación correcta pero el display esta apagado. Display Dañado.',
    '7/13/2022,1018,Preventivo,,,,',
    '7/14/2022,Del Este,Preventivo,,,Se verifico estado de panel solar y baterías.,',
    '7/15/2022,Ñuñorco TELGECS - COD,Alarma,Alarma de batería baja,Sí,Se levantaron 3 postes caidos de la línea que lleva 220Vca a la casilla que esta en la cumbre del cerro. Se procedio a puentear llave térmica en el medidor de servicio ya que la misma se encuentra dañada.,Se solicita el reemplazo de la llave térmica dañada en el medidor',
    '12/15/2022,Casa Rosada,Sin comunicación,Sin alimentación de 220Vca,No,Caja de control y RTU apagadas ya que no llega alimentación de 220vca a caja de protección.,no aplica.',
    '2/9/2022,Cevil Pozo,Sin comunicación,registrador sin comunicación,Sí,Se reconfiguró velocidad del analizador.,',
    '4/26/2022,Cevil Pozo,Sin comunicación,A determinar,No,"Se cambio radiomodem, antena y coaxial pero no se llego a una solución",Posible falla en la Repetidora del Este TELGECS.',
    '7/19/2022,4538,Mala comunicación,antena mal orientada,Sí,Se reorienta antena.,',
    '7/19/2022,2692,Preventivo,,,,Gabinete de Punto fijo sin PAT. Durante la tarea no se pudo conectar la PAT ya que el unico punto de vinculación se encuentra cerca del transformador.',
    '2/9/2022,Choromoro,Sin comunicación,Equipo sin comunicación,No,Se encontro caja de control apagada sin alimentación de 220Vca,',
    '7/20/2022,780,Preventivo,,,,',
    '7/20/2022,3283,Preventivo,,,,',
    '7/20/2022,104,Preventivo,,,,',
    '7/20/2022,4006,Preventivo,,,,',
    '7/21/2022,7147,Otros,Registros atrasado,Sí,Se reconfiguro capacidad de placa RTU,',
    '2/17/2022,COD Operaciones,Sin comunicación,Sin alimentación de 220Vca,Sí,Se normalizo disyuntor actuado en tablero general.,',
    '7/21/2022,910,Preventivo,,,,Se reemplazo batería por estar agotada.',
    '7/21/2022,1939,Preventivo,,,,',
    '7/22/2022,566,Mala comunicación,a determinar,Sí,Se reemplazo radiomodem,',
    '7/22/2022,765,Preventivo,,,No se pudo ingresar a la propiedad privada donde se encuentra la SET,Tambien se visito el sitio el día 21/7 y no se pudo ingresar.',
    '7/22/2022,1314,Preventivo,,,Se reemplaza batería por estar agotada. Se reemplaza placa de control por entregar valores bajo de tensión para la carga de batería.,',
    '7/22/2022,452,Preventivo,,,,',
    '7/22/2022,454,Preventivo,,,,',
    '1/19/2022,Colonia 1,Sin comunicación,Actuadas llaves térmicas de la protección y de la caja derivadora.,Sí,Se levantaron ambas llaves.,',
    '7/25/2022,626,Otros,Caja de protección dañada sin la sujeción para poste,Sí,Se instalo sujeción para poste en caja de protección,',
    '7/26/2022,1124,Mala comunicación,A determinar,No,"Se cambio radiomodem, se reoriento antena pero no se logro dar solucion ",Queda pendiente de solucion',
    '7/26/2022,C. del 25 TELGECS,Preventivo,ninguno,Sí,Se verifico el estado de la base TELGECS para descartar posibles problemas ya que la SET 1124 presenta mala comunicación al igual que la SET 1173. Ambas en la misma zona.,',
    '3/7/2022,Concepción,Sin comunicación,Conversor Rs232 a RS 485 dañado.,Sí,Se reemplazo conversor.,',
    '7/27/2022,Del Este,Preventivo,,,,',
    '4/22/2022,Concepción,Sin comunicación,Conversor TCP/IP con falla,Sí,Se reemplazo conversor TCP/IP,',
    '7/28/2022,981,Preventivo,,,,',
    '7/29/2022,3267,Preventivo,,,,',
    '8/1/2022,Lules 2,Alarma,El rebaje presentaba alarma de I. Max de Distr. V. del Carmen y Alarma Intermitente de Uca Calefaccion. Se encontraron placa ED18 Dañada y ED32 Sulfatada con fallas,Sí,Se reemplazaron placas ED 18 ty ED32 y se realizo limpieza de las placas que presentaban sulfato pero no fallas.,',
    '4/28/2022,Concepcion 2,Sin comunicación,Rec de entrada y distr. Sin comunicación,No,"Se instalo fuentes para conversores y baterías, es necesario regresar para terminar con la tarea.  ",',
    '4/29/2022,Concepcion 2,Sin comunicación,Rec de entrada y distr. Sin comunicación,Sí,Se termino con la tarea iniciada el 28/04. quedan con comunicación los distribuidores y el Rec de entrada.,Se instala fuente particular para conversores en cada caja de control.',
    '8/2/2022,2735,Preventivo,,,,',
    '8/2/2022,6311,Preventivo,,,,',
    '8/29/2022,Concepcion 2,Sin comunicación,Placa RTU de control y conversores de todos los reconectadores quemados,Sí,Se realizo el reemplazo de Placa RTU de control y 4 conversores 232-485,',
    '12/6/2022,Concepcion 2,Sin comunicación,Sin comunicación distribuidores. Sin lectura señalizaciones de placas RTU,Sí,Se reemplazo conversor dañado e integrados de comunicación en placa de control. Se reemplazo Rtu de control.,no aplica',
    '8/3/2022,1173,Mala comunicación,A determinar,No,Se probó reemplazando el radiomodem pero no mejoroó la comunicación.,No aplica',
    '8/3/2022,4863,Preventivo,,,,',
    '8/3/2022,2120,Preventivo,,,,',
    '8/3/2022,1923,Preventivo,,,,',
    '8/4/2022,Amaicha,Alarma,Alarmas intermitentes de UCA los Zazos y alimentación Encalilla,Sí,UCA los Zazos se reparó plaqueta y alimentación Encalilla se reseteo caja de control de reconectador 4C,',
    '8/4/2022,6743,Preventivo,,,,',
    '8/5/2022,3143,Mala comunicación,Registrador con comunicación intermitente,Sí,Se dio aviso a la guardia de calidad y servicio que procedio..Se colocó uno de manera provisoria 383719043,',
    '8/5/2022,6442,Alarma,Falta fase,Sí,Se cambio placa de proteción y de control,',
    '8/8/2022,Trancas - COD,Preventivo,se visita base ya que algunos equipos que se comunican atraves de ella presentan mala comunicación,Sí,Cambio de radiomodem,',
    '8/9/2022,3212,Preventivo,,,,',
    '8/9/2022,3532,Preventivo,,,,',
    '8/9/2022,3056,Preventivo,,,,',
    '8/9/2022,Der. A Mista,Otros,No se ejecutan los comandos.,No,"Se realizaron pruebas de comando,determinando que la RTU los envía correctamente",',
    '8/10/2022,1122,Preventivo,,,,',
    '8/10/2022,1587,Preventivo,,,,',
    '8/10/2022,194,Preventivo,,,,',
    '8/10/2022,1619,Preventivo,,,,',
    '8/10/2022,797,Preventivo,,,,',
    '2/7/2022,Concepción 2,Sin comunicación,Distribuidores y Rec de entrada sin comunicación,Sí,"Se encontraron fuentes auxiliares del Distr. Alpachiri y Rec de entrada dañadas, no se alimenta conversor. ",',
    '2/17/2022,Concepción 2,Sin comunicación,Sin comuncacion distribuidores y Rec de entrada.,Sí,"Se cambiaron conversores en reconectadores. Distribuidor G. Matorras queda sin comunicación, queda previsto regresar a realizar pruebas sobre dicho reconectador. ",',
    '8/11/2022,Solar del Cerro,Preventivo,,,,Se realizó limpieza y cambio de baterías',
    '2/18/2022,Concepción 2,Sin comunicación,Distribuidor G. Matorras sin comunicación .,Sí,Se reemplazo fusible en fuente auxiliar y conversor Rs485,',
    '3/7/2022,Concepción 2,Sin comunicación,Rec de entrada y distr. Sin comunicación,Sí,"Se resuelve el problema de comunicación de los distribuidores cambiando el conversor RS 485 del Distr. Alpachiri. El Rec de entrada posee fuente auxiliar dañada, no se puede alimentar el conversor, queda sin comunicación. ",',
    '8/12/2022,2030,Mala comunicación,Antena o cable coaxial dañados.,No,No se pudo realizar el trabajo debido a la proximidad de la antena a los cables de media tensión.,Se tendría que programar un corte en MT para poder solucionar el problema.',
    '3/14/2022,Concepción 2,Sin comunicación,Sin comunicación todo el rebaje,Sí,"Se cambio fusible en placa RTU de control. Se cambio integrado 485 en puerto de comunicación del Distr. Habitad. Se encontro fuente auxiliar dañada en Distr. G. Matorras. No se logro restablecer la comunicación del Dist. Alpachiri, queda pendiente de solución. ",',
    '8/16/2022,4621,Preventivo,,,,',
    '8/16/2022,6085,Preventivo,,,,',
    '8/16/2022,6845,Preventivo,,,,',
    '8/17/2022,El Mollar,Otros,Dos relés de 220Vca y una placa ED12-4C dañadas.,Sí,Se reemplazaron los relés y la placa.,',
    '8/17/2022,3466,Preventivo,,,,',
    '8/18/2022,4507,Preventivo,,,,',
    '8/18/2022,4505,Preventivo,,,,',
    '8/18/2022,4340,Preventivo,,,,',
    '8/18/2022,4704,Preventivo,,,,',
    '8/18/2022,545,Preventivo,,,,',
    '8/19/2022,463,Preventivo,,,,',
    '5/24/2022,Concepción 2,Sin comunicación,Distribuidor Alpachiri sin comunicación,Sí,Se reemplaza conversor dañado.,Se Instalo batería de respaldo (12Vcc) para el conversor de comunicación en cada caja de control.',
    '8/19/2022,2276,Preventivo,,,,',
    '8/19/2022,1676,Preventivo,,,,',
    '8/22/2022,476,Preventivo,,,,',
    '8/22/2022,402,Preventivo,,,,',
    '8/22/2022,6968,Preventivo,,,,',
    '8/22/2022,773,Preventivo,,,,se instalo vinculación de PAT.',
    '8/23/2022,Trancas TELGECS  Operaciones,Otros,Traslado de Antenas.,Sí,Se sealiza el transalado de las antenas de las bases de Operaciones y TELGECS a la nueva torre.,',
    '8/24/2022,La Bolsa,Preventivo,,,,',
    '8/24/2022,,Preventivo,,,,',
    '8/24/2022,Elias Perez,Preventivo,,,,No se llevo a cabo la tarea ya que en el sitio se encontraban realizando una obra vial.',
    '8/24/2022,Casa Rosada,Preventivo,,,,',
    '8/24/2022,4211,Preventivo,,,,',
    '8/24/2022,4255,Preventivo,,,,',
    '8/25/2022,Raco,Preventivo,,,,',
    '8/25/2022,La Comuna,Preventivo,,,,',
    '5/27/2022,Concepción 2,Sin comunicación,Rec de entrada y distr. Sin comunicación,Sí,Se reemplazo conversor e integrado de comunicación por estar dañados.,En el día de hoy personal de EDET trabajo sobre el Rec de entrada.',
    '8/26/2022,Trancas - Operaciones,Preventivo,,,,Se reemplazo batería.',
    '8/26/2022,Leocadio Paz,Preventivo,,,,',
    '8/26/2022,4251,Preventivo,,,,',
    '6/8/2022,Concepción 2,Sin comunicación,Sin comunicación Rec de entrada y Distribuidores.,Sí,Se reemplazo conversor de comunicación dañado en el Rec. De entrada.,',
    '7/11/2022,Concepción 2,Sin comunicación,"Se encontro dañado: Placa RTU de Control, Integrados de comunicación de integrados, conversores de comunicación en los distribuidores y el Rec. De Entrada.",Sí,"Se realizo el reemplazo de La placa RTU de Control, integrados de comuncacion y conversores dañados. El Distri. G. Matorras queda pendiente de solución. ",Nos indican desde el COD que la Falta de comunicación coincide con una falla en el Distr. Habitad.',
    '7/12/2022,Concepción 2,Sin comunicación,Sin comunicación Distr. G. Matorras,Sí,Se cambio conversor de comunicación.,',
    '8/30/2022,1808,Preventivo,,,,',
    '9/6/2022,Concepción 2,Sin comunicación,Distribuidores sin comunicación,Sí,Se reemplazaron placa de control RTUCTRL y 5 conversores.,no aplica',
    '8/31/2022,San Miguel,Preventivo,,,,',
    '8/31/2022,Colombres,Preventivo,,,,',
    '8/31/2022,Delfín Gallo,Preventivo,,,No se pudo realizar el trabajo debido a algunos cables que hay en la columna e impiden ubicar la escalera con seguridad.,',
    '9/1/2022,El Cochuchal,Preventivo,no aplica,,no aplica,no aplica',
    '12/1/2022,Concepción 2,Sin comunicación,Rec de entrada sin comunicación. Conversor dañado.,Sí,Se reemplazo conversor RS232/485 dañado,No aplica',
    '12/12/2022,Concepción 2,Sin comunicación,Distribuidores y Rec de entrada sin comunicación,Sí,Se reemplazaron conversores dañados en las cajas de control,no aplica.',
    '1/3/2022,Concepcíon 2,Sin comunicación,Sin comunicación Distri. Matorras y Habitad,No,No se logro dar solución. Se trae placa RTU de control para ser revisada en Digicom. Se informa a COD que rebaje queda sin comunicación.,',
    '1/4/2022,Concepcíon 2,Sin comunicación,Todo el rebaje esta sin comuniacion,No,"Se analizaron diferentes motivos de la falla, se reemplazaron conversores y placa RTU pero no se logro dar una solución. Queda pendiente regresar al sitio a continuar con los trabajos. ",',
    '9/7/2022,2818,Preventivo,no aplica,,no aplica,no aplica',
    '9/7/2022,917,Preventivo,no aplica,,no aplica,no aplica',
    '9/8/2022,1972,Preventivo,no aplica,,no aplica,no aplica',
    '1/5/2022,Concepcíon 2,Sin comunicación,Todo el rebaje esta sin comuniacion,No,"Se trabajo en el sitio pero no se logro dar solución, queda previsto regresar a continuar con los trabajos. ",',
    '9/9/2022,Colombres,Mala comunicación,Radiomodem con problemas,Sí,Se reemplazó radiomodem.,no aplica',
    '1/6/2022,Concepcíon 2,Sin comunicación,Todo el rebaje esta sin comuniacion,Sí,Se cambiaron conversores e integrados RS485 en placa RTU de control. El Distr. G. Matorras queda sin comunicación debido a que posee fuente Auxiliar de 28Vcc dañada y no se puede alimentar el conversor de comunicaciones.,',
    '9/9/2022,4041,Preventivo,no aplica,,no aplica,no aplica',
    '9/9/2022,4417,Preventivo,no aplica,,no aplica,no aplica',
    '3/25/2022,Concepcíon 2,Sin comunicación,Distribuidor Alpachiri sin comunicación,No,Se realizaron varias pruebas con diferentes posibles soluciones y no se logro restablecer la comunicación. Queda previsto regresar al sitio.,',
    '1/18/2022,Concepción II,Sin comunicación,Sin comunicación Distribuidores Alpachiri y Habitad,Sí,El Distribuidor Habitad queda sin comunicación debido a que posee fuente Auxiliar de 28 Vcc dañada y no se puede alimentar el conversor de comunicaciones.,La fuente auxiliar del Distribuidor Alpachiri entrega 34 Vcc en vez de 28.',
    '9/12/2022,1875,Preventivo,no aplica,,no aplica,no aplica',
    '9/12/2022,1045,Preventivo,no aplica,,no aplica,no aplica',
    '9/12/2022,146,Preventivo,no aplica,,no aplica,no aplica',
    '9/12/2022,575,Preventivo,no aplica,,no aplica,no aplica',
    '9/13/2022,2464,Otros,Archivo con faltante de registros.,Sí,Se reemplazo placa RTU,Se tendra este equipo en revision',
    '12/15/2022,Concepción II,Sin comunicación,"Sin comunicación RTU,Medidores y Reconectadores",Sí,Se reemplazo placa RTU-CTRL,no aplica',
    '9/16/2022,7027,Preventivo,no aplica,,no aplica,Se realizó limpieza y cambio de baterías',
    '12/19/2022,Concepción II,Sin comunicación,Sin comunicación Rec. De entrada y distribuidores,Sí,Se determino que el modulo de comunicación del Rec.de entrada se encuentra dañado y dejaba sin comunicación los distribuidores.Se dejo desconectado cable de comunicación del Rec. De entrada,no aplica',
    '9/19/2022,6066,Otros,Registrador sin configuracion.,Sí,Se reconfiguro registrador,A solicitud del Ing. C. Toranzo se reconfiguro el registrador de dicha SET.',
    '8/3/2022,Constitucion y Ruta 9,Sin comunicación,ninguno,No,Al llegar al sitio se verifica que la caja de control del reconectador fue desmontada.,',
    '10/18/2022,Constitucion y Ruta 9,Sin comunicación,Falta cable coaxial y antena obstruida.,Sí,Se coloco un cable coaxial y se reoriento antena.,La antena se encontraba obstruida por equipo de la linea de fibra optica.',
    '12/21/2022,Cristo rey,Sin comunicación,Proteccion dañada. Reconectador sin alimentacion.,No,Se encontro protección dañada y termica actuada,Se da aviso a personal de Equipo Eléctrico',
    '9/20/2022,Ampimpa - Operaciones,Otros,baterias de respaldo de los equipos de Noanet agotadas.,Sí,Se reemplazo banco de baterías.,no aplica',
    '8/11/2022,Cuesta del 25 (COD),Sin comunicación,Térmica del medidor actuada,Sí,Se levantó la térmica del medidor,En el sitio se encontró mucha suciedad de ratas que pudieron haber causado que salte la térmica',
    '9/21/2022,9288,Otros,Alarma de Tensión superiror al maximo,No,Se verifico que las tensiones de las fases se encuentran variando entorno al valor limite superior de tension (230Vca),"Vr= 231Vca, Vs= 230Vca, Vt= 231Vca"',
    '8/11/2022,Cuesta del 25 (TELGECS),Sin comunicación,Térmica del medidor actuada,Sí,Se levantó la térmica del medidor,En el sitio se encontró mucha suciedad de ratas que pudieron haber causado que salte la térmica',
    '9/21/2022,1739,Otros,no aplica,Sí,no aplica,Se realizo relevamiento del la SET para coordinar el translado de la misma.',
    '3/11/2022,Der. A Raco,Sin comunicación,Equipo sin comunicación,Sí,Se cambio Radiomodem,',
    '9/22/2022,2713,Otros,errores de comunicación momentaneos y aleatorios.,Sí,"Al llegar al sitio se encontro que el equipo estaba con comunicación correcta. Se verificaron tensiones, conexiones y configuraciones del punto fijo y no se encontro una posible causa del problema que se presenta de manera momentanea y de manera aleatoria. ",no aplica',
    '9/23/2022,1739,Otros,no aplica,Sí,Se realizo el translado del punto fijo a otra SET.,no aplica',
    '9/26/2022,Der. A Mista,Otros,No se ejecutan los comandos de apertura y cierre,No,Se realizaron pruebas con balija de prueba provista por equipo electrico y se determino que los comandos no salen de la placa RTU.,Queda pendiente de coordinar una tarea para realizar el cambio de placa RTU y probar los telecomnandos.',
    '9/26/2022,Lules 2,Mala comunicación,errores de comunicación momentaneos y aleatorios.,Sí,al llegar al sito las placas RTU se encontraban con comunicación correcta. Se realizo limpieza de placas RTU ED 32 que presentaban sulfato debido a la humedad.,no aplica',
    '9/27/2022,Los Ralos,Alarma,Alarma intermitente de Uca RTU,Sí,Se retocaron soldaduras de placa RTU ED-12 N°2,no aplica',
    '9/27/2022,Simoca,Otros,Medidones intercambiadas entre el Distri. Balderrama y TPN°,Sí,Se realizo el cambio desde el sistema SCADA. Se verifico el cambio con personal en el sitio.,no aplica',
    '9/27/2022,Pampa Mayo,Preventivo,no aplica,,no aplica,no aplica',
    '9/27/2022,7960,Preventivo,no aplica,,no aplica,no aplica',
    '9/28/2022,Santo Domingo,Mala comunicación,errores de comunicación momentaneos y aleatorios.,Sí,Se reemplazo radiomodem,no aplica',
    '9/28/2022,Monteros,Preventivo,no aplica,,no aplica,no aplica',
    '9/28/2022,Lules 2,Preventivo,no aplica,Sí,no aplica,Queda previsto regresar a sellar una filtración de agua en el gabinete.',
    '11/8/2022,El Arsenal,Sin comunicación,A determinar,Sí,Se reemplazo radiomodem,Se realizaron pruebas de señalizacion: Supervisión y Recierre.',
    '4/20/2022,El Cruce,Sin comunicación,Sin alimentación de 220Vca,Sí,Se encendio placa de encendido que se encontraba apagada. Se controlaron las alimentaciones y se encuentran correctas.,Repetidora de comunicaciones de NOANET.',
    '9/29/2022,Lules 2,Otros,Filtraciones,Sí,Se regreso a sellar filtraciones de agua en el gabinete,no aplica',
    '4/25/2022,El Cruce,Sin comunicación,Placa cargadora dañada,No,Se trae placa cargadora a Digicom para ser reparada.,Repetidora de comunicaciones de NOANET.',
    '4/26/2022,El Cruce,Sin comunicación,Placa cargadora dañada,Sí,Se reemplazo placa cargadora,Repetidora de comunicaciones de NOANET.',
    '8/13/2022,El Mollar,Sin comunicación,Varias partes dañadas.,No,Se cambiaron placa de RTU-CTRL y radiomodem.,"Se encontraron dañados dos relés de 220Vca y una placa ED12-4C, que serán reemplazados en una próxima visita. Se hicieron limpieza, verificación de baterías y de fuente de alimentación. Se constató que el medidor de 33Kv estaba quemado y el de Casas Viejas sin comunicación."',
    '9/30/2022,La Providencia,Alarma,No llega tensión de servicos auxiliares a gabiente RTU ya que una fase de tensión que alimenta la cabina se encontraba cortada en el exterior.,Sí,Se dio aviso a guardia quien soluciono el problema. Se verifico el buen funcionaiento de la RTU luego que se restablecio el servicio.,no aplica',
    '12/22/2022,El Mollar,Sin comunicación,Sin comunicación RTU y medidores,Sí,Se reemplazo RTU,No aplica',
    '10/3/2022,2741,Preventivo,no aplica,,no aplica,no aplica',
    '10/3/2022,7609,Preventivo,no aplica,,no aplica,no aplica',
    '5/16/2022,Escaba - TELGECS,Sin comunicación,Equipo apagado.,Sí,se sufrio vandalismo en la cabina y en el gabinete de la repetidora y sustrajeron el banco de baterías de respaldo. Se reacondiciono el gabinete y se colocaron baterias nuevas.,',
    '3/11/2022,Fortunata Garcia,Sin comunicación,Equipo sin comunicación,No,No se logra llevar a cabo la tarea ya que se  imposibilita colocar la escalera para trabajar debido a cables con tension por debajo de la caja de control.,',
    '5/24/2022,Fortunata Garcia,Sin comunicación,Sin alimentación de 220Vca,Sí,Personal de Equipo Eléctrico reemplazo fusibles dañados en caja de protección. Al recuperar la alimentacionde 220Vca se observa que el equipo queda con Mala comunicación por lo tanto se cambia radiomodem pero no surge efecto. No se puede revisar cable coaxial y antena por su proximidad a la LMT. Queda tarea pendiente.,El reconectador queda con mala comunicación.',
    '10/5/2022,1909,Preventivo,no aplica,Sí,no aplica,no aplica',
    '3/9/2022,Gastona Norte,Sin comunicación,Alarma de ausencia 220Vca,Sí,,',
    '4/14/2022,Gastona Sur,Sin comunicación,Falso contacto en alimentación de radiomodem,Sí,Se corrigió el falso contacto en los cable de alimentación de radiomodem.,',
    '8/29/2022,Gastona Sur,Sin comunicación,Placa de encendido dañada,Sí,Se realizo el reemplazo de la placa de encendido,',
    '8/19/2022,GPRS 010,Sin comunicación,RTU sin comunicación. Placa sulfatada.,Sí,Se reemplazó placa de RTU.,',
    '1/8/2022,Burruyacu,Sin lectura,Distribuidores y Rec de entrada sin lectura. Placa Multipuerto dañada,Sí,Se reemplazo placa multipuerto.,Personal de turno de BRS no sinforman que previo a quedar sin ectura ocurrio una falla en el Distr. Burruyacu.',
    '10/21/2022,La Comuna,Sin comunicación,Antena de Repetidora Las Tuquitas mal orientada,Sí,Se reoriento y ajusto antena en Repetidora las Tuquitas.,Este reconectador se comunica a traves de la repetidora las tuquitas.',
    '10/11/2022,Mariño,Otros,Nos solicitaron revisar el equipo ya que el dia 15/09 al realizar maniobra de cierre quedo sin comunicación.,Sí,Se realizo la verificacion completa del equipo y no se encontrop una posible falla que ocacione la perdida de comuncacion.,quedaria pendiente realizar verificaciones en el momento que se realice una maniobra sobre el seccionador.',
    '10/11/2022,3164,Preventivo,no aplica,,no aplica,no aplica',
    '10/11/2022,3224,Preventivo,no aplica,,no aplica,no aplica',
    '10/12/2022,Lules 2,Otros,no aplica,Sí,Se instalo resistencia de calefaccion deltro del API,no aplica-',
    '10/12/2022,Santa Lucia,Alarma,Alarma de Temperatura superior al maximo,Sí,Se reemplazo sensor de temperatura,no aplica',
    '12/13/2022,La Florida,Sin comunicación,Placa RTU de Control y Medidor sin comunicación,Sí,se reconfiguro placa RTU de Control.,No aplica.',
    '1/26/2022,La Loma,Sin comunicación,Caja de control apagada. Llave térmica de proteccion actuada.,No,Se Normaliza llave térmica pero no enciende la caja de control.,Se da aviso a personal de Equipo Eléctrico',
    '1/21/2022,La Riva,Sin comunicación,A determinar,Sí,Se cambio radiomodem,',
    '10/13/2022,765,Preventivo,no aplica,Sí,no aplica,no aplica',
    '10/13/2022,280,Preventivo,no aplica,No,no se pudo llevar a cabo la tarea ya que en la base del poste donde esta el punto fijo se ejecuta una obra civil de urbanización,no aplica',
    '10/13/2022,1035,Alarma,Alarma: Nivel de tensión RTU superior al maximo.,Sí,Se reemplazo placa de control,no aplica',
    '10/13/2022,971,Preventivo,no aplica,Sí,no aplica,no aplica',
    '10/13/2022,379,Preventivo,no aplica,Sí,no aplica,no aplica',
    '10/13/2022,5956,Preventivo,no aplica,Sí,no aplica,no aplica',
    '10/14/2022,Taco Ralo,Preventivo,no aplica,Sí,no aplica,se reemplazo banco de batrías de 24vcc',
    '10/14/2022,3641,Alarma,Alarma: Tensión de RTU superior al máximo,Sí,se reemplazo Placa de control,no aplica',
    '10/17/2022,4852,Otros,no aplica,Sí,se nos solicito realizar la inspección del la SET ya que en próximos trabajos se realizara cambio de transformador.,seran necesarios 4 mts de cable para medidicon de corrientes y 4mts de cable para medicion de tensiones.',
    '10/17/2022,Las Tuquitas,Preventivo,no aplica,Sí,no aplica,no aplica',
    '10/17/2022,6685,Preventivo,no aplica,Sí,no aplica,no aplica',
    '10/18/2022,1065,Mala comunicación,No baja registros.,Sí,Se reemplazo radiomodem,no aplica',
    '10/18/2022,1065,Preventivo,no aplica,,no aplica,no aplica',
    '1/19/2022,La Rural,Sin comunicación,Antena rodeada por la copa de un árbol impide buena comunicación.,Sí,"Se cambió canal de radio, orientación de antena y batería.","Debido al árbol, la comunicación no es muy buena."',
    '10/18/2022,1124,Mala comunicación,errores de comunicacon intermitente,No,Se realizaron diversos pruebas pero no se logra a una solucion,Es necesario realizr un corte de energia y la utilizacion de una barquilla para acceder hasta la antena y berificar su estado.',
    '10/18/2022,Las Salinas,Preventivo,no aplica,No,no aplica,no aplica',
    '10/19/2022,Concepcion - TELGECS,Otros,Alguno equipos que se comunican por esta base se encuentran sin comunicación.,No,Se realizo reemplazo de radiomodem,No se logra recuperar la comnicacion de los equipos',
    '2/3/2022,La Trinidad,Sin comunicación,Medidores,No,"Se mide alimentación de los medidores 117Vca, por lo tanto los medidores no encienden.",',
    '10/19/2022,La Trinidad,Sin comunicación,a determinar,Sí,Se reemplazo radiomdemy levantaron las comunicaciones pero con algunos errores,Queda previsto regresar y verificar estado de antena.',
    '11/14/2022,Las Marías,Sin comunicación,A determinar,Sí,Se modifico repetidora de comunicación asociada,no aplica.',
    '10/20/2022,La Trinidad,Mala comunicación,Antena dañada,Sí,Se reemplazo antena,no aplica.',
    '5/2/2022,Las Talitas,Sin comunicación,Placa RTU sin comunicación.,Sí,Se ajustaron cables de comunicación en borneras de la placa RTU.,',
    '6/6/2022,Legumbres,Sin comunicación,Llave térmica actuada en caja de protección,No,Se prueba comunicación del radiomodem con una batería externa y funciona correctamente.,Se da aviso a Equipo Eléctrico sobre la alimentación de la caja de control.',
    '10/21/2022,8809,Preventivo,no aplica,,no aplica,no aplica',
    '10/21/2022,Barrio Soeme,Mala comunicación,Linea de vista obstruida,Sí,Se cambio canal de comunicación,no aplica',
    '10/21/2022,629,Preventivo,no aplica,,no aplica,no aplica',
    '6/6/2022,Legumbres,Sin comunicación,Configuración de comunicaciones en caja de control F6,Sí,Se regresa por la tarde luego que Equipo Eléctrico soluciono el problema de alimentación. Se realiza configuracion de comunicación y se realizan pruebas de telecontrol con el COD.,',
    '10/22/2022,4852,Otros,Se modifica SET de Monofásica a Trifásica,Sí,Se realizo el movimiento de Punto Fijo en la SET y se reconfiguro registrador como Trifásico.,No aplica',
    '3/7/2022,Los Agudos,Sin comunicación,Placa RTU dañada,No,Se trae placa RTU para ser reparada en Digicom.,',
    '3/9/2022,Los Agudos,Sin comunicación,Placa RTU dañada,Sí,Se reemplaza placa RTU,',
    '6/22/2022,Los Agudos,Sin comunicación,A determinar,No,Se probo cambiando radiomodem y no se verifico el estado del cable coaxial por estar antena cerca de la LMT. No se logro una solución,En el día de mañana se visitara base de comunicación para verificar su funcionamiento.',
    '6/23/2022,Los Agudos,Sin comunicación,error de comunicación,Sí,Se cambio canal de comuniación por Base Ñuñorco.,',
    '10/25/2022,2013,Alarma,Ausencia de Fase,Sí,se cambio placa de control,no aplica.',
    '4/27/2022,Los Ralos,Sin comunicación,Distribuidor Los Ralos,Sí,Se normalizo llave térmica actuada en la alimentación de la caja de control.,',
    '10/25/2022,548,Mala comunicación,Linea de Vista obstruida,Sí,Se reemplazo antena y cable coaxial y mejoro un gran porcentaje la comunicación-,La linea de vista se encuentra obstruida por arboles alrededor del equipo.',
    '10/25/2022,897,Preventivo,no aplica.,Sí,no aplica.,no aplica.',
    '10/25/2022,799,Preventivo,no aplica.,Sí,no aplica.,no aplica.',
    '1/15/2022,Los Ralos - Operaciones,Sin comunicación,Mal funcionamiento del conversor.,Sí,Se reemplazó conversor.,',
    '10/26/2022,,,,,,',
    '10/26/2022,,,,,,',
    '10/27/2022,Solar del Cerro,Mala comunicación,Linea de vista obstruida,Sí,Se cambio repetidora de comunicación asociada,no aplica',
    '10/27/2022,Las Marías,Mala comunicación,Linea de vista obstruida,Sí,Se cambio repetidora de comunicación asociada,no aplica',
    '1/17/2022,Los Ralos - Operaciones,Sin comunicación,Dañada fuente de alimentación y batería agotada.,Sí,Se cambió fuente y batería.,',
    '10/28/2022,,,,,,',
    '10/28/2022,,,,,,',
    '10/28/2022,,,,,,',
    '10/31/2022,Lules 2,Otros,Banco de Baterias de 24Vcc agotado,Sí,Se reemplazo banco de baterías.,Se colocaron dos baterías de 12 vcc 55Ah.',
    '11/13/2022,Los Vallistos,Sin comunicación,Fusible XS en la entrada del Transformador de Servicios Auxiliares abierto. Fase que alimenta al rectificador con 37Vca,Sí,Guardia normalizo estado del Fusible XS y luego se verifico el correcto funcionamiento de la RTU.,Luego de estar varia horas sin tensión de servicos auxiliares se agoto batería de RTU por lo que la misma fue reemplazada.',
    '11/1/2022,Ñuñorco COD y TELGECS,Alarma,Tensión de Radiomodem Inferior a la minima.,Sí,"Se encontro cable de alimentacion de 220Vca que entra a la cabina con falla, queda pendiente reemplazar dicho cable. ",no aplica.',
    '11/2/2022,Villa Nogues C1 - TELGECS,Otros,Equipos alejados de la base se encuentran con problemas de comunicación,No,Se reemplaza radiomodem pero no se logra mejorar la comunicación de los equipos.,Los Puntos fijos sin comunicación pertenecen a administración Concepcion.',
    '2/7/2022,Lules,Sin comunicación,Medidores sin comunicación,Sí,Se corrigio el cableado de comunicación de todos los medidores,',
    '7/28/2022,Lules,Sin comunicación,Rec de Entrada TR2 sin comunicación,Sí,Se cambio conversor,',
    '11/28/2022,Lules,Sin comunicación,Llave termica de Servicos Auxiliares actuada en el API,Sí,Se normalizo llave térmica,Queda pendiente de resolver una alarma intermitente de Uca Medidores TR1',
    '12/5/2022,Lules,Sin comunicación,Placa RTU de Control y Medidores sin comunicación,Sí,se reconfiguro placa RTU de Control.,no aplica',
    '12/6/2022,Lules,Sin comunicación,A determinar,Sí,Se reemplazo radiomodem,no aplica',
    '12/15/2022,Lules,Sin comunicación,Rec. De entrada TR2 sin comunicación,Sí,Se reemplazo conversor RS232/485,no aplica',
    '11/4/2022,Raco,Otros,Rec de entrada no responde a los comandos.,Sí,Equipo Eléctrico nos solicita estar presente en el sitio durante la verificación de la caja de control del reconectador. Se desvinculo caja de control de caja de conjunción.,retiraron caja de control de Rec de entrada',
    '12/19/2022,Lules,Sin comunicación,Rec. De entrada TR2 sin comunicación,Sí,Se reemplazo conversor RS232/485,no aplica',
    '12/12/2022,Lules,Sin comunicación,Rec. De entrada TR2 sin comunicación,Sí,Se reemplazo conversor RS232/485,no aplica',
    '8/30/2022,Lules 2,Sin comunicación,Placa RTU de control con mal funcionamiento,Sí,Se realizo el reemplazo de Placa RTU de control,',
    '11/8/2022,Solar del Cerro,Otros,Llave térmica Ucc Gral. Se ecuentra dañada,Sí,Se reemplaca llave Térmica,no aplica',
    '11/8/2022,Lules 2,Otros,Nos solicitan desde sucursal EDET Lules verificar el motivo por el cual la llave Térmica Uca General se actuo en reiteradas ocaciones.,Sí,Se realizaron las verifivacaiones correspondientes y no se encontro un motivo que ocaciones el accionar de la llave térmica. Se procedio a reemplazar dicha llave.,no aplica',
    '9/9/2022,Lules 2,Sin comunicación,Placa RTUCTRL y registradores sin comunicación,Sí,Mal contacto de ficha de alimentación de RTUCTRL. Se reemplazó.,no aplica',
    '9/21/2022,Lules 2,Sin comunicación,Placa RTU de control sin Comuniacion,Sí,Se reconfiguro placa,no aplica',
    '6/22/2022,Malvinas,Sin comunicación,A determinar,No,Se probo cambiando radiomodem y no se logro una solución,En el día de mañana se visitara base de comunicación para verificar su funcionamiento.',
    '11/9/2022,1716,Preventivo,no aplica,,no aplica,no aplica',
    '11/9/2022,7453,Preventivo,no aplica,,no aplica,no aplica',
    '4/13/2022,Manantial,Sin comunicación,Rec de entrada y distr. Sin comunicación,Sí,Se cambio conversor dañado en Distr. Soberanía.,',
    '11/10/2022,Blas Parera,Preventivo,no aplica,,no aplica,Se reemplazo batería 12Vx12Ah',
    '11/10/2022,San Ramon,Preventivo,no aplica,,no aplica,"Se realizaron pruebas de Señalización: Supervisión, Recierre y Alimentación. "',
    '11/10/2022,Wilde,Preventivo,no aplica,,no aplica,"Se realizaron pruebas de Señalización: Supervisión, Recierre y Alimentación. "',
    '11/10/2022,Canal Sur,Preventivo,no aplica,,no aplica,"Se realizaron pruebas de Señalización: Supervisión, Recierre y Alimentación. "',
    '11/11/2022,1791,Otros,Traslado,Sí,Se realizo el translado del punto fijo a otra SET.,solicitamos el número de la nueva SET como el código correspondiente a la misma para configurarlo en el sistema SCADA',
    '3/11/2022,Manatial,Sin comunicación,Todo el rebaje esta sin comuniacion,Sí,Al llegar al sitio se restablecio la comuniación. No se determino una posible causa del problema.,',
    '1/28/2022,Mariño,Sin comunicación,Equipo sin comunicación,No,Se encuentra control RTU y radiomodem con mal funcionamiento. Se desmonta control y Radiomodem para ser revisado en Digicom,',
    '2/26/2022,Mariño,Sin comunicación,Placa RTU y radiomodem dañado.,No,Se suspende tarea con corte programado ya que solo se desenergizo la linea de un solo lado.,',
    '11/14/2022,334,Preventivo,no aplica,,no aplica,no aplica',
    '4/1/2022,Mariño,Sin comunicación,Placa RTU y radiomodem dañado.,Sí,Se instalo rtu reparada y radiomodem nuevo.,',
    '11/14/2022,49,Preventivo,no aplica,,no aplica,no aplica',
    '11/15/2022,765,Alarma,Tensión inferior al mínimo en fase S y T,Sí,Se cambio ficha enchufable en placa de protección por estar dañada.,no aplica',
    '11/15/2022,La Higuerita,Preventivo,no aplica,Sí,no aplica,Se reemplazo batería 12x12Ah',
    '11/15/2022,Via Ruta 336,Mala comunicación,Errores de comunicación intermitentes,Sí,Se cambio radiomodem pero no se soluciono el problema. Es necesario verificar el estado de la Antena y cable Coaxial.,Por la cercania con la linea no se puede acceder hasta la ubicación de la antena. Se solicita un corte de energia y una barquilla para realizar la tarea.',
    '4/5/2022,Mariño,Sin comunicación,Placa cargadora dañada,Sí,Se reemplazo placa cargadora.,',
    '11/17/2022,Peron,Preventivo,no aplica,,no aplica,no aplica',
    '11/17/2022,Arr. San Javier,Preventivo,no aplica,,no aplica,no aplica',
    '11/17/2022,Vialidad,Preventivo,no aplica,,no aplica,no aplica',
    '11/17/2022,8244,Preventivo,no aplica,,no aplica,Gabinete de Punto fijo sin PAT. Durante la tarea no se pudo conectar la PAT ya que el unico punto de vinculación se encuentra cerca del transformador.',
    '11/17/2022,503,Preventivo,no aplica,,no aplica,no aplica',
    '11/17/2022,3285,Preventivo,No se pudo realizar servicio preventivo ya que una edificación impide el acceso hasta el gabinete de Punto Fijo,,no aplica,Se solicita dentro de lo posible el traslado o reubicacion del gabinete de punto fijo.',
    '4/26/2022,Mariño,Sin comunicación,Placa de encendido y protección dañada,Sí,Se repararon placas,Se observa que los gabinetes RTU poseen instaladas correctamente su vinculación a tierra.',
    '11/18/2022,Monteros - COD,Mala comunicación,A determinar,Sí,Se reemplazo radiomodem,no aplica',
    '7/8/2022,Mollar,Sin comunicación,Placa RTU de control desconfigurada,Sí,Se procedio a reconfigurar placa RTU de control. También se ajustaron cables de alimentación con falso contacto.,',
    '9/5/2022,Mollar,Sin comunicación,no aplica,Sí,Se reemplazó placa de control RTUCTRL.,no aplica',
    '1/21/2022,Monseñor Díaz,Sin comunicación,Proteccion dañada. Reconectador sin alimentacion.,No,se da aviso a personal de Equipo Eléctrico sobre el estado de la protección del reconecatdor.,',
    '11/7/2022,Monteros,Sin comunicación,"Problemas ocurridos el domingo 6/11 causaron daño rompiendo Placa DDP, Placa Multipuerto y puerto de comunicación de rec TR1 y TR2 ",Sí,Se reemplazo placa DDP por una RTU de Control y se restablecio la comunicación de los medidores.,RTU Harris también fueros dañadas.',
    '11/16/2022,Monteros,Sin comunicación,RTU Harris sin comunicación.,Sí,Se nos solicito conectar RTU Harris (verificadas previamente por personal de EDET) a placa de control RTU para verificar si logra comunicarse. Se probaron diferetes modos de conexión y en ningun momento se logro restablecer la comunicación de las RTU Harris.,Esperamos comunicación para coordinar una futura tarea en el sitio.',
    '11/23/2022,Mancopa,Preventivo,no aplica,,no aplica,Se reemplazo batería de 12Vcc 12Ah.',
    '11/18/2022,Monteros,Sin comunicación,RTU Harris sin comunicación.,Sí,Se restablecio comunicación de RTU Harris reacondicionada,Queda pendiente restablecer la comunicación de los Medidores.',
    '11/22/2022,Monteros,Sin comunicación,Medidores sin comunicacion,Sí,Se instalo placa DDP,Se logro retablecer comunicación de RTU Harris y Medidores.',
    '11/24/2022,3675,Preventivo,no aplica,,,No se pudo acceder hasta la SET por el mal estado del camino',
    '11/25/2022,Banda Rio Sali - COD,Preventivo,no aplica,,No aplica,Se reemplazo batería de 12Ah por una de 22Ah.',
    '12/12/2022,Monteros,Sin comunicación,RTU Harris sin comunicación.,Sí,Se reemplazo conversor RS232/485,no aplica.',
    '11/25/2022,,,,,,',
    '4/26/2022,Prevision - A - CAM,Sin comunicación,radiomodem con nivel bajo de señal,Sí,Se reemplazo radiomodem,',
    '11/28/2022,3854,Preventivo,no aplica,,no aplica,no aplica',
    '11/28/2022,1176,Preventivo,no aplica,,no aplica,no aplica,no aplica.',
    '11/29/2022,Lules,Alarma,Alarma: Uca Medidores TR1,Sí,Se reemplazo placa RTU ED18,no aplica',
    '7/21/2022,Prevision - A y B - CAM,Sin comunicación,Cable de alimentación de 220Vca cortado,Sí,Se empalmo cable de alimentación cortado.,',
    '12/1/2022,Monteros,Mala comunicación,a determinar,Sí,Se reemplazo radiomodem,no aplica',
    '6/23/2022,Previsión - A y B - CAM,Sin comunicación,Llave térmica actuada en tablero general,Sí,Se normalizo llave térmica. Solo recupero comunicación Previsión B. Queda previsto regresar a dar solución a la Rpt Previsión A,',
    '12/2/2022,Lado Sur de Arcor,Alarma,"Alarmas: Ausencia de 220Vca, Batería Baja",Sí,Se reemplazo placa de encendido y placa cargadora dañadas.,no aplica',
    '3/9/2022,Previsión A (CAM),Sin comunicación,radiomodem sin comunicación,No,Se probo cambiando radiomodem y se verifico el buen estado del cable coaxial. No se logro una solución,Queda previsto regresar al sitio.',
    '3/14/2022,Previsión A (CAM),Sin comunicación,radiomodem sin comunicación,Sí,Se cambio radiomodem por problema de comunicación.,',
    '2/22/2022,Previsión A y B (CAM),Sin comunicación,Sin alimentación de 220Vca,No,No se pudo ingresar hasta los equipos ya que  el personal de mantenimiento eléctrico del edificio de Previsión Social se encuantra de licencia. Nos solicitaron regresar el día de mañana 23/02,',
    '2/23/2022,Previsión A y B (CAM),Sin comunicación,Sin alimentación de 220Vca,Sí,Se.,',
    '12/16/2022,Radio Nacional,Sin comunicación,Sin alimentación de 220Vca,No,Caja de control y RTU apagadas ya que no llega alimentación de 220vca a caja de protección.,Hormigas en caja de control y caja de protrcción-Cuchillas de entrada y salida abiertas - Linea con By pass',
    '12/6/2022,1460,Alarma,Ausencia de Fase,Sí,Se reemplazo placa de protección,se encontro nido de pajaros dentro de la caja de protección.',
    '2/1/2022,Rec. Leocadio Paz,Sin comunicación,antena mal orientada y con elementos dañados.,Sí,Se logro reorientar antena solo unos grados y levanto la comuncacion.,Se observa en el sitio que fue instalado un cable de tension por el lugar donde esta la antena que no permite orientarla con la direccion correcta.Se solicita quitar cable de ese lugar.',
    '12/7/2022,Constitución y Ruta 9,Mala comunicación,Cable coaxial dañado.,Sí,Se reemplazo cable coaxial,Se encontro el cable coaxial cortado',
    '12/7/2022,Arsenal,Mala comunicación,Antena mal orientada,Sí,Se reoriento antena,no aplica.',
    '3/8/2022,Ricchio,Sin comunicación,Placa de protección dañada y fuente de alimentación de radiomodem desconectada.,Sí,Se reparo placa de protección y se conecto entada de 220vca a fuente de radiomodem.,',
    '3/18/2022,Ricchio,Sin comunicación,Placa de protección dañada.,Sí,,',
    '6/21/2022,Ruta 9 y 321,Sin comunicación,A determinar,No,"Se cambio radiomodem, antena y coaxial pero no se llego a una solución",Se verificara base de comuncación y repetidora asociada.',
    '6/24/2022,Ruta 9 y 321,Sin comunicación,error de comunicación,Sí,Se cambio canal de comuniación por Base Ñuñorco.,',
    '2/11/2022,San Pablo,Sin comunicación,Sin comunicación Rec de entrada y Distribuidores. Solano Vera y Rinconada,Sí,Se cambiaron conversores de Rec. de entrada y Rec. Solano Vera. Se reemplazo integrado de comunicación en Rec. Rinconada.,',
    '12/13/2022,6134,Preventivo,no aplica,,no aplica,no aplica',
    '3/16/2022,San Pablo,Sin comunicación,"Distri. Solano Vera, La inconada y rec de entrada sin comunicación. ",Sí,Se cambio conversor 485/232 en Rec de entrada.,',
    '12/14/2022,Trancas - COD,Preventivo,no aplica,,no aplica,Se reemplazo fuente por entregar valores bajos de tensión',
    '12/14/2022,Trancas,Preventivo,no aplica,,no aplica,no aplica',
    '12/14/2022,2829,Preventivo,no aplica,,no aplica,no aplica',
    '7/18/2022,San Pablo,Sin comunicación,Sin comunicación Rec de entrada TR2 y distribuidorres Solano Vera y Rinconada,Sí,Se reemplazaron integrados de comunicación 485 de la placa de RTU de control ya que los mismos estaban dañados.,',
    '7/25/2022,San Pablo,Sin comunicación,Sin comunicación reconectador de entrada y distri. Solano vera y Rinconada,Sí,Se cambiaron conversores RS232 a RS485 y los Integrados de comunicación 485 en placa RTU de control por estar dañados debido a una sobretension por as lineas de comunicacion correspondientes al ReC de entrada TR2 y al Distr. Rinconada.,Personal de guardia en el sitio el día de la perdida de comunicación nos da aviso de este problema luego que se quiso cerrar el Rec de entrada TR2',
    '12/13/2022,San Pablo,Sin comunicación,Rec de entrada y distribuidor,,,',
    '12/16/2022,San Pablo,Sin comunicación,Sin comunicación Rec. De entrada,Sí,Se reemplazo conversor RS232/485,no aplica',
    '12/19/2022,San Pablo,Sin comunicación,Sin comunicación Rec. De entrada,Sí,Se reemplazo integrado 485 en placa RTU-CTRL,no aplica',
    '3/15/2022,San Pedro - TELGECS,Sin comunicación,Placa de encendido dañada,Sí,Se reemplazo placa de encendido,Se encontro panal de avispas dentro del gabinete.',
    '12/16/2022,482,Mala comunicación,Errores de comunicacon intermitente,No,Se realizaron diversos pruebas pero no se logra a una solucion,no aplica',
    '12/16/2022,2228,Preventivo,no aplica,,no aplica,no aplica',
    '1/19/2022,San Ramón,Sin comunicación,Equipo sin comunicación,Sí,Se cambió canal de radio y orientación de antena.,',
    '1/7/2022,Solar del Cerro,Sin comunicación,Todo el CD sin comunicación,Sí,Se reemplaza antena.,',
    '8/2/2022,Taco Ralo,Sin comunicación,Con Alarm de ausencia de 220Vca. Placa de encendido dañada.,Sí,Se reemplazo placa de encendido por tener varistores dañados por sobretensión.,',
    '12/20/2022,Trancas - COD,Mala comunicación,A determinar,Sí,Se reemplazo conversor TCP/IP,no aplica',
    '12/20/2022,7113,Otros,nivel bajo de señal en radiomodem,Sí,Se reemplazo radiomodem,no aplica',
    '12/22/2022,Tafi del Valle,Sin comunicación,Sin comunicación medidor salida del trafo,No,Se verificó en el sitio ID y cables de comunicación del medidor.El equipo no marca tensión ni corrientes y muestra potencia negativa,No aplica',
    '12/21/2022,Manantial,Otros,Nos indican de sucursal Lules que el reconectador R. de la Plata indica abierto cuando en sistema SCADA figura cerrado.,Sí,Al llegar al sitio se verifica que la caja de control indica reconectador cerrado coincidiendo con el sistema SCADA,Se verifico que las corrientes del ditri. R. de la Plata coinciden con el medidor en el sitio.',
    '5/3/2022,Trancas - COD,Sin comunicación,Conversor TCP/IP con falla,Sí,Se reemplazo conversor.,',
    '8/26/2022,Trancas - TELGECS,Sin comunicación,Batería dañada,Sí,Se reemplazo batería,',
    '12/14/2022,Trancas - TELGECS,Sin comunicación,Placa de encendido dañada,Sí,Se reemplazo placa de encendido,Se actualizo batería.',
    '12/21/2022,6654,Preventivo,no aplica,,no aplica,No aplica',
    '10/12/2022,Trinidad,Sin comunicación,A determinar,Sí,Se reemplazo radiomdem,no aplica',
    '11/25/2022,Trinidad,Sin comunicación,Dstribuidor,,,',
    '12/22/2022,581,Preventivo,no aplica,,no aplica,Se actualizo batería.',
    '10/31/2022,Via Ruta 336,Sin comunicación,Equipos apagados. Proteccion dañada. Batería de 12vcc (RTU) agotada.,No,Se reemplazo batería y se probaron las comunicaciones del gabinete RTU con resultados correctos.,no aplica',
    '6/24/2022,Villa Fiad,Sin comunicación,Medidor sin comunicación,No,Se verifico que llega alimentación de 220Vca pero el registrador no enciende.,',
    '12/23/2022,1173,Mala comunicación,A determinar,No,Se probó reemplazando el radiomodem pero no mejoroó la comunicación.,No aplica',
    '12/23/2022,2345,Preventivo,No aplica,,No aplica,No aplica',
    '12/23/2022,1758,Preventivo,No aplica,,No aplica,No aplica',
    '12/26/2022,482,Mala comunicación,Errores de comunicacon intermitente,Sí,Se reemplazó antena y cable coaxial mejorando la comunicación,No aplica',
    '7/6/2022,Villa Fiad,Sin comunicación,Medidor sin comunicación,Sí,Se reemplazo medidor,Solo mide corrientes. Las tensiones de medición no llegan desde el TV.',
    '12/27/2022,6089,Preventivo,No aplica,,No aplica,No aplica',
    '12/27/2022,Monteros,Mala comunicación,RTU Harris con mala comunicación,Sí,Se reemplazo conversor RS232/485,No aplica',
    '10/5/2022,Villa Lujan,Sin comunicación,A determinar,Sí,Se reemplazo radiomodem,no aplica',
    '10/6/2022,Villa Lujan,Sin comunicación,Linea de vista obstruida.,Sí,Se cambio canal de comunicación,no aplica',
    '12/28/2022,4223,Preventivo,No aplica,,No aplica,No aplica',
    '12/28/2022,4231,Mala comunicación,Errores de comunicación,No,Se reemplazó radiomodem.,No aplica',
    '6/22/2022,Villa Nogues 4 - CAM,Sin comunicación,radiomodem sin comunicación,Sí,Se reemplazo radiomodem,',
    '12/28/2022,548,Mala comunicación,Linea de vista obstruida,No,Se reemplazo radiomodem,Queda pendiente brindar una solución',
    '12/29/2022,Estática Sur,Preventivo,No aplica,,No aplica,Descarga de datos.',
    '12/29/2022,Sarmiento,Preventivo,No aplica,,No aplica,Descarga de datos.',
    '12/29/2022,Alderetes,Alarma,"Alamas de ausencia de UCA 380V, UCA medidores UCA calefacción",No,Se reemplazó placa RTU-ED 12 N°1,UCA 380V sigue ausente..Verificar sensor',
    '12/29/2022,R. Los Bulacios,Otros,Estado del reconectador sin estados.Funcionamiento incorrecto.Reconectador abierto D.,No,En el sitio se verifican que estas señales/Estados estan reflejados en el panel frontal de la caja de control,Se da aviso a personal de Equipo Eléctrico',
    '12/30/2022,Gastona Norte,Otros,Nos solicitaron revisar el equipo,Sí,Personal de DIGICOM realizo pruebas de telecomando no encontrando ninguna falla en nuestra RTU,Protección dañada..Se dio aviso a Equipos electricos',
    '12/30/2022,1872,Preventivo,No aplica,,No aplica,Se actualizo batería.',
    '12/30/2022,3385,Preventivo,No aplica,,No aplica,No aplica',
]

export { servicios }