export const EQUIPOS_SECCIONADOR_TABLE = {
  administracion: "Administracion",
  sucursal: "Sucursal",
  localidad: "Localidad",
  direccion: "Direccion",
  tipo: "Tipo",
  nombre: "Nombre",
  ultima_visita: "Ultima Visita",
  marca_modelo: "Marca, modelo",
  id_sistema: "ID Sistema",
  id_rtu: "ID RTU",
  id_radio: "ID Radio",
  id_master: "ID Master",
  canal_radio: "Canal de radio",
  rpt_directo: "Por RPT/Directo",
  rpt_asociado: "RPT asociado",
  v_prim: "V Prim",
  v_seccionador: "V Seccionador",
  distribuidor: "Distribuidor",
  configuracion: "Config",
  piquete: "Piquete",
  latitud_sur: "Latitud Sur",
  latitud_oeste: "Latitud Oeste",
  orientacion_antena: "Orientacion Antena",
  fecha_instalacion: "Fecha instalacion",
  fecha_cambio_bateria: "Cambio de bateria",
  numero_serie: "Numero de serie",
  numero_serie_reemplazo: "Nro. de serie reemplazo",
  velocidad_rtu: "Velocidad RTU",
  numero_serie_radio_modem: "Nro. de serie RM",
  observaciones: "Observaciones",
};
export const EQUIPOS_TELGEC_TABLE = {
    administracion: "Administracion",
    sucursal: "Sucursal",
    localidad: "Localidad",
    direccion: "Direccion",
    nro_set: "SET",
    codigo_caja: "Codigo Caja",
    ultima_visita: "Ultima Visita",
    v_prim: "V Prim",
    configuracion: "Config",
    t_m: "T/M",
    numero_serie_medidor: "Nro. Serie Medidor",
    canal_radio: "Canal de radio",
    rpt_directo: "Por RPT/Directo",
    rpt_asociado: "RPT asociado",
    id_rtu: "ID RTU",
    id_modbus: "ID Modbus",
    id_radio: "ID Radio",
    id_master: "ID Master",
    latitud_sur: "Latitud Sur",
    latitud_oeste: "Latitud Oeste",
    orientacion_antena: "Orientacion Antena",
    fecha_instalacion: "Fecha instalacion",
    fecha_cambio_bateria: "Cambio de bateria",
    numero_serie: "Numero de serie",
    numero_serie_reemplazo: "Nro. de serie reemplazo",
    placa_radio_modem: "Placa de RM",
    numero_serie_radio_modem: "Nro. de serie RM",
    programa_radio_modem: "Programa de RM",
    radio_modem_protegido: "RM protegido",
    velocidad_rtu: "Velocidad RTU",
    capacidad_rtu: "Capacidad RTU",
    observaciones: "Observaciones",
  };